# This file was auto-generated by Fern from our API Definition.

from ..core.client_wrapper import SyncClientWrapper
import typing
from ..types.instrument_status import InstrumentStatus
import datetime as dt
from ..core.request_options import RequestOptions
from ..types.market_search_response import MarketSearchResponse
from ..core.datetime_utils import serialize_datetime
from ..core.pydantic_utilities import parse_obj_as
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.http_validation_error import HttpValidationError
from json.decoder import JSONDecodeError
from ..core.api_error import ApiError
from ..types.market_lookup_response import MarketLookupResponse
from ..types.market_search_result import MarketSearchResult
from ..core.client_wrapper import AsyncClientWrapper


class MarketsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def search_markets(
        self,
        *,
        q: typing.Optional[str] = None,
        exchange_name: typing.Optional[str] = None,
        category: typing.Optional[typing.Sequence[str]] = None,
        subcategory: typing.Optional[str] = None,
        status: typing.Optional[InstrumentStatus] = None,
        expiration_date_start: typing.Optional[dt.datetime] = None,
        expiration_date_end: typing.Optional[dt.datetime] = None,
        start_datetime_after: typing.Optional[dt.datetime] = None,
        start_datetime_before: typing.Optional[dt.datetime] = None,
        event_ticker: typing.Optional[str] = None,
        sort_by: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        event_limit: typing.Optional[int] = None,
        event_offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MarketSearchResponse:
        """
        Search and browse markets across all exchanges.

        Supports:
        - Exact match on ticker, condition_id, slug, river_id
        - Full-text search on name, description, tags
        - Browse by filters (no query required)
        - Results ranked by relevance

        We default to active markets in the view so things are faster

        Parameters
        ----------
        q : typing.Optional[str]
            Search query

        exchange_name : typing.Optional[str]
            Filter by exchange name (KALSHI, POLYMARKET)

        category : typing.Optional[typing.Sequence[str]]
            Filter by canonical category. Repeat the param to filter to multiple categories (Sports, Crypto, Politics, Finance, Entertainment, Science & Tech, Weather, World Affairs, Health, Social, Other).

        subcategory : typing.Optional[str]
            Filter by subcategory (e.g. Basketball, Football)

        status : typing.Optional[InstrumentStatus]
            Filter by instrument status

        expiration_date_start : typing.Optional[dt.datetime]
            Start of expiration date range (inclusive, ISO 8601)

        expiration_date_end : typing.Optional[dt.datetime]
            End of expiration date range (exclusive, ISO 8601)

        start_datetime_after : typing.Optional[dt.datetime]
            Filter to markets with start_datetime >= this (ISO 8601)

        start_datetime_before : typing.Optional[dt.datetime]
            Filter to markets with start_datetime < this (ISO 8601)

        event_ticker : typing.Optional[str]
            Filter by event_ticker (exact match)

        sort_by : typing.Optional[str]
            Sort mode for event-based pagination: trending, volume, newest, ending-soon, start-time

        limit : typing.Optional[int]
            Maximum number of results

        offset : typing.Optional[int]
            Offset for pagination

        event_limit : typing.Optional[int]
            Paginate by events instead of markets. Up to 200 by default; values above that require start_datetime_after or start_datetime_before.

        event_offset : typing.Optional[int]
            Event offset for event-based pagination

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MarketSearchResponse
            Successful Response

        Examples
        --------
        from rivermarkets import RiverMarkets

        client = RiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )
        client.markets.search_markets()
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/markets/search",
            method="GET",
            params={
                "q": q,
                "exchange_name": exchange_name,
                "category": category,
                "subcategory": subcategory,
                "status": status,
                "expiration_date_start": serialize_datetime(expiration_date_start)
                if expiration_date_start is not None
                else None,
                "expiration_date_end": serialize_datetime(expiration_date_end)
                if expiration_date_end is not None
                else None,
                "start_datetime_after": serialize_datetime(start_datetime_after)
                if start_datetime_after is not None
                else None,
                "start_datetime_before": serialize_datetime(start_datetime_before)
                if start_datetime_before is not None
                else None,
                "event_ticker": event_ticker,
                "sort_by": sort_by,
                "limit": limit,
                "offset": offset,
                "event_limit": event_limit,
                "event_offset": event_offset,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    MarketSearchResponse,
                    parse_obj_as(
                        type_=MarketSearchResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def lookup_markets(
        self, *, river_ids: str, request_options: typing.Optional[RequestOptions] = None
    ) -> MarketLookupResponse:
        """
        Batch lookup markets by river_ids.

        Parameters
        ----------
        river_ids : str
            Comma-separated list of river IDs

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MarketLookupResponse
            Successful Response

        Examples
        --------
        from rivermarkets import RiverMarkets

        client = RiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )
        client.markets.lookup_markets(
            river_ids="river_ids",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/markets/lookup",
            method="GET",
            params={
                "river_ids": river_ids,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    MarketLookupResponse,
                    parse_obj_as(
                        type_=MarketLookupResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def match_market(
        self,
        *,
        ticker: typing.Optional[str] = None,
        slug: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MarketSearchResult:
        """
        Exact match a single market by Kalshi ticker or Polymarket slug. Supply exactly one.

        Parameters
        ----------
        ticker : typing.Optional[str]
            Exact Kalshi ticker (e.g. KXNBA-26-DET)

        slug : typing.Optional[str]
            Exact Polymarket slug (e.g. will-the-denver-nuggets-win-the-2026-nba-finals)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MarketSearchResult
            Successful Response

        Examples
        --------
        from rivermarkets import RiverMarkets

        client = RiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )
        client.markets.match_market()
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/markets/match",
            method="GET",
            params={
                "ticker": ticker,
                "slug": slug,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    MarketSearchResult,
                    parse_obj_as(
                        type_=MarketSearchResult,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)


class AsyncMarketsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def search_markets(
        self,
        *,
        q: typing.Optional[str] = None,
        exchange_name: typing.Optional[str] = None,
        category: typing.Optional[typing.Sequence[str]] = None,
        subcategory: typing.Optional[str] = None,
        status: typing.Optional[InstrumentStatus] = None,
        expiration_date_start: typing.Optional[dt.datetime] = None,
        expiration_date_end: typing.Optional[dt.datetime] = None,
        start_datetime_after: typing.Optional[dt.datetime] = None,
        start_datetime_before: typing.Optional[dt.datetime] = None,
        event_ticker: typing.Optional[str] = None,
        sort_by: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        event_limit: typing.Optional[int] = None,
        event_offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MarketSearchResponse:
        """
        Search and browse markets across all exchanges.

        Supports:
        - Exact match on ticker, condition_id, slug, river_id
        - Full-text search on name, description, tags
        - Browse by filters (no query required)
        - Results ranked by relevance

        We default to active markets in the view so things are faster

        Parameters
        ----------
        q : typing.Optional[str]
            Search query

        exchange_name : typing.Optional[str]
            Filter by exchange name (KALSHI, POLYMARKET)

        category : typing.Optional[typing.Sequence[str]]
            Filter by canonical category. Repeat the param to filter to multiple categories (Sports, Crypto, Politics, Finance, Entertainment, Science & Tech, Weather, World Affairs, Health, Social, Other).

        subcategory : typing.Optional[str]
            Filter by subcategory (e.g. Basketball, Football)

        status : typing.Optional[InstrumentStatus]
            Filter by instrument status

        expiration_date_start : typing.Optional[dt.datetime]
            Start of expiration date range (inclusive, ISO 8601)

        expiration_date_end : typing.Optional[dt.datetime]
            End of expiration date range (exclusive, ISO 8601)

        start_datetime_after : typing.Optional[dt.datetime]
            Filter to markets with start_datetime >= this (ISO 8601)

        start_datetime_before : typing.Optional[dt.datetime]
            Filter to markets with start_datetime < this (ISO 8601)

        event_ticker : typing.Optional[str]
            Filter by event_ticker (exact match)

        sort_by : typing.Optional[str]
            Sort mode for event-based pagination: trending, volume, newest, ending-soon, start-time

        limit : typing.Optional[int]
            Maximum number of results

        offset : typing.Optional[int]
            Offset for pagination

        event_limit : typing.Optional[int]
            Paginate by events instead of markets. Up to 200 by default; values above that require start_datetime_after or start_datetime_before.

        event_offset : typing.Optional[int]
            Event offset for event-based pagination

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MarketSearchResponse
            Successful Response

        Examples
        --------
        import asyncio

        from rivermarkets import AsyncRiverMarkets

        client = AsyncRiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.markets.search_markets()


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/markets/search",
            method="GET",
            params={
                "q": q,
                "exchange_name": exchange_name,
                "category": category,
                "subcategory": subcategory,
                "status": status,
                "expiration_date_start": serialize_datetime(expiration_date_start)
                if expiration_date_start is not None
                else None,
                "expiration_date_end": serialize_datetime(expiration_date_end)
                if expiration_date_end is not None
                else None,
                "start_datetime_after": serialize_datetime(start_datetime_after)
                if start_datetime_after is not None
                else None,
                "start_datetime_before": serialize_datetime(start_datetime_before)
                if start_datetime_before is not None
                else None,
                "event_ticker": event_ticker,
                "sort_by": sort_by,
                "limit": limit,
                "offset": offset,
                "event_limit": event_limit,
                "event_offset": event_offset,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    MarketSearchResponse,
                    parse_obj_as(
                        type_=MarketSearchResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def lookup_markets(
        self, *, river_ids: str, request_options: typing.Optional[RequestOptions] = None
    ) -> MarketLookupResponse:
        """
        Batch lookup markets by river_ids.

        Parameters
        ----------
        river_ids : str
            Comma-separated list of river IDs

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MarketLookupResponse
            Successful Response

        Examples
        --------
        import asyncio

        from rivermarkets import AsyncRiverMarkets

        client = AsyncRiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.markets.lookup_markets(
                river_ids="river_ids",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/markets/lookup",
            method="GET",
            params={
                "river_ids": river_ids,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    MarketLookupResponse,
                    parse_obj_as(
                        type_=MarketLookupResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def match_market(
        self,
        *,
        ticker: typing.Optional[str] = None,
        slug: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MarketSearchResult:
        """
        Exact match a single market by Kalshi ticker or Polymarket slug. Supply exactly one.

        Parameters
        ----------
        ticker : typing.Optional[str]
            Exact Kalshi ticker (e.g. KXNBA-26-DET)

        slug : typing.Optional[str]
            Exact Polymarket slug (e.g. will-the-denver-nuggets-win-the-2026-nba-finals)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MarketSearchResult
            Successful Response

        Examples
        --------
        import asyncio

        from rivermarkets import AsyncRiverMarkets

        client = AsyncRiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.markets.match_market()


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/markets/match",
            method="GET",
            params={
                "ticker": ticker,
                "slug": slug,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    MarketSearchResult,
                    parse_obj_as(
                        type_=MarketSearchResult,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)
