# This file was auto-generated by Fern from our API Definition.

import typing
from ..core.client_wrapper import SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.complex_order_list_response import ComplexOrderListResponse
from ..core.pydantic_utilities import parse_obj_as
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.http_validation_error import HttpValidationError
from json.decoder import JSONDecodeError
from ..core.api_error import ApiError
from ..types.conditional_order_create import ConditionalOrderCreate
from ..types.iceberg_order_params import IcebergOrderParams
from ..types.peg_order_params import PegOrderParams
from ..types.smart_taker_order_params import SmartTakerOrderParams
from ..types.complex_order_create_response import ComplexOrderCreateResponse
from ..core.serialization import convert_and_respect_annotation_metadata
from ..types.cancel_complex_order_response import CancelComplexOrderResponse
from ..types.complex_order_response import ComplexOrderResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.client_wrapper import AsyncClientWrapper

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ComplexOrdersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_complex_orders(
        self,
        *,
        complex_order_type: typing.Optional[str] = None,
        status: typing.Optional[typing.Sequence[str]] = None,
        river_id: typing.Optional[int] = None,
        generic_asset_id: typing.Optional[str] = None,
        subaccount_id: typing.Optional[str] = None,
        complex_order_ids: typing.Optional[typing.Sequence[str]] = None,
        parent_river_order_id: typing.Optional[str] = None,
        unparented_only: typing.Optional[bool] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ComplexOrderListResponse:
        """
        List complex orders (conditional and iceberg) with optional filters.

        Returns a dict keyed by complex order type (`conditional_orders`,
        `iceberg_orders`). Use `complex_order_type` to restrict to one type.

        Parameters
        ----------
        complex_order_type : typing.Optional[str]
            Filter by complex order type: CONDITIONAL, TWAP, ICEBERG, PEG.

        status : typing.Optional[typing.Sequence[str]]
            Filter by status name. Interpreted per complex_order_type (ConditionalOrderStatus for CONDITIONAL, IcebergOrderStatus for ICEBERG, PegOrderStatus for PEG). Unknown names for the active type are ignored.

        river_id : typing.Optional[int]
            Filter by instrument ID

        generic_asset_id : typing.Optional[str]
            Filter by generic asset basket ID

        subaccount_id : typing.Optional[str]
            Filter to a specific subaccount

        complex_order_ids : typing.Optional[typing.Sequence[str]]
            Filter by complex order IDs

        parent_river_order_id : typing.Optional[str]
            Filter by parent order ID

        unparented_only : typing.Optional[bool]
            When true, only return conditional orders with no parent_river_order_id (standalone stops). Ignored for non-conditional types.

        limit : typing.Optional[int]
            Results per page (max 1000)

        offset : typing.Optional[int]
            Pagination offset

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ComplexOrderListResponse
            Successful Response

        Examples
        --------
        from rivermarkets import RiverMarkets

        client = RiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )
        client.complex_orders.list_complex_orders()
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/complex-orders",
            method="GET",
            params={
                "complex_order_type": complex_order_type,
                "status": status,
                "river_id": river_id,
                "generic_asset_id": generic_asset_id,
                "subaccount_id": subaccount_id,
                "complex_order_ids": complex_order_ids,
                "parent_river_order_id": parent_river_order_id,
                "unparented_only": unparented_only,
                "limit": limit,
                "offset": offset,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    ComplexOrderListResponse,
                    parse_obj_as(
                        type_=ComplexOrderListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def create_complex_order(
        self,
        *,
        subaccount_id: str,
        river_id: typing.Optional[int] = OMIT,
        generic_asset_id: typing.Optional[str] = OMIT,
        conditional_order_params: typing.Optional[ConditionalOrderCreate] = OMIT,
        iceberg_order_params: typing.Optional[IcebergOrderParams] = OMIT,
        peg_order_params: typing.Optional[PegOrderParams] = OMIT,
        smart_taker_order_params: typing.Optional[SmartTakerOrderParams] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ComplexOrderCreateResponse:
        """
        Create a new complex order (conditional or iceberg).

        Provide exactly one of `conditional_order_params` (TP/SL/STOP) or
        `iceberg_order_params`. The body shape determines the complex_order_type.

        Returns 202 Accepted with the persisted complex order in PENDING status,
        enqueued for activation by the appropriate consumer service.

        Parameters
        ----------
        subaccount_id : str
            Subaccount to create the order under

        river_id : typing.Optional[int]
            Instrument ID. Mutually exclusive with generic_asset_id.

        generic_asset_id : typing.Optional[str]
            Generic asset basket ID. Mutually exclusive with river_id.

        conditional_order_params : typing.Optional[ConditionalOrderCreate]
            Conditional order parameters (TP/SL/STOP)

        iceberg_order_params : typing.Optional[IcebergOrderParams]
            Iceberg order parameters

        peg_order_params : typing.Optional[PegOrderParams]
            Peg order parameters

        smart_taker_order_params : typing.Optional[SmartTakerOrderParams]
            Smart-taker order parameters

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ComplexOrderCreateResponse
            Successful Response

        Examples
        --------
        from rivermarkets import RiverMarkets

        client = RiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )
        client.complex_orders.create_complex_order(
            subaccount_id="subaccount_id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/complex-orders",
            method="POST",
            json={
                "subaccount_id": subaccount_id,
                "river_id": river_id,
                "generic_asset_id": generic_asset_id,
                "conditional_order_params": convert_and_respect_annotation_metadata(
                    object_=conditional_order_params,
                    annotation=ConditionalOrderCreate,
                    direction="write",
                ),
                "iceberg_order_params": convert_and_respect_annotation_metadata(
                    object_=iceberg_order_params,
                    annotation=IcebergOrderParams,
                    direction="write",
                ),
                "peg_order_params": convert_and_respect_annotation_metadata(
                    object_=peg_order_params,
                    annotation=PegOrderParams,
                    direction="write",
                ),
                "smart_taker_order_params": convert_and_respect_annotation_metadata(
                    object_=smart_taker_order_params,
                    annotation=SmartTakerOrderParams,
                    direction="write",
                ),
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    ComplexOrderCreateResponse,
                    parse_obj_as(
                        type_=ComplexOrderCreateResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def cancel_all_complex_orders(
        self,
        *,
        subaccount_id: str,
        river_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CancelComplexOrderResponse:
        """
        Cancel all cancellable complex orders (conditional and iceberg) for a subaccount.

        Returns the list of complex_order_ids that were submitted for cancellation.

        Parameters
        ----------
        subaccount_id : str
            Subaccount to cancel all complex orders for

        river_ids : typing.Optional[typing.Sequence[int]]
            If set, only cancel cancellable complex orders for these instruments. Must be either omitted/null or a non-empty list.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CancelComplexOrderResponse
            Successful Response

        Examples
        --------
        from rivermarkets import RiverMarkets

        client = RiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )
        client.complex_orders.cancel_all_complex_orders(
            subaccount_id="subaccount_id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/complex-orders/cancel-all",
            method="POST",
            json={
                "subaccount_id": subaccount_id,
                "river_ids": river_ids,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    CancelComplexOrderResponse,
                    parse_obj_as(
                        type_=CancelComplexOrderResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def get_complex_order(
        self,
        complex_order_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ComplexOrderResponse:
        """
        Get a single complex order by ID (conditional or iceberg).

        Parameters
        ----------
        complex_order_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ComplexOrderResponse
            Successful Response

        Examples
        --------
        from rivermarkets import RiverMarkets

        client = RiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )
        client.complex_orders.get_complex_order(
            complex_order_id="complex_order_id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/complex-orders/{jsonable_encoder(complex_order_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    ComplexOrderResponse,
                    parse_obj_as(
                        type_=ComplexOrderResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def cancel_complex_order(
        self,
        complex_order_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CancelComplexOrderResponse:
        """
        Cancel a single complex order (conditional or iceberg).

        Returns 202 Accepted. Cancellation is processed asynchronously by the
        appropriate consumer service.

        Parameters
        ----------
        complex_order_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CancelComplexOrderResponse
            Successful Response

        Examples
        --------
        from rivermarkets import RiverMarkets

        client = RiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )
        client.complex_orders.cancel_complex_order(
            complex_order_id="complex_order_id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/complex-orders/{jsonable_encoder(complex_order_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    CancelComplexOrderResponse,
                    parse_obj_as(
                        type_=CancelComplexOrderResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)


class AsyncComplexOrdersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_complex_orders(
        self,
        *,
        complex_order_type: typing.Optional[str] = None,
        status: typing.Optional[typing.Sequence[str]] = None,
        river_id: typing.Optional[int] = None,
        generic_asset_id: typing.Optional[str] = None,
        subaccount_id: typing.Optional[str] = None,
        complex_order_ids: typing.Optional[typing.Sequence[str]] = None,
        parent_river_order_id: typing.Optional[str] = None,
        unparented_only: typing.Optional[bool] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ComplexOrderListResponse:
        """
        List complex orders (conditional and iceberg) with optional filters.

        Returns a dict keyed by complex order type (`conditional_orders`,
        `iceberg_orders`). Use `complex_order_type` to restrict to one type.

        Parameters
        ----------
        complex_order_type : typing.Optional[str]
            Filter by complex order type: CONDITIONAL, TWAP, ICEBERG, PEG.

        status : typing.Optional[typing.Sequence[str]]
            Filter by status name. Interpreted per complex_order_type (ConditionalOrderStatus for CONDITIONAL, IcebergOrderStatus for ICEBERG, PegOrderStatus for PEG). Unknown names for the active type are ignored.

        river_id : typing.Optional[int]
            Filter by instrument ID

        generic_asset_id : typing.Optional[str]
            Filter by generic asset basket ID

        subaccount_id : typing.Optional[str]
            Filter to a specific subaccount

        complex_order_ids : typing.Optional[typing.Sequence[str]]
            Filter by complex order IDs

        parent_river_order_id : typing.Optional[str]
            Filter by parent order ID

        unparented_only : typing.Optional[bool]
            When true, only return conditional orders with no parent_river_order_id (standalone stops). Ignored for non-conditional types.

        limit : typing.Optional[int]
            Results per page (max 1000)

        offset : typing.Optional[int]
            Pagination offset

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ComplexOrderListResponse
            Successful Response

        Examples
        --------
        import asyncio

        from rivermarkets import AsyncRiverMarkets

        client = AsyncRiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.complex_orders.list_complex_orders()


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/complex-orders",
            method="GET",
            params={
                "complex_order_type": complex_order_type,
                "status": status,
                "river_id": river_id,
                "generic_asset_id": generic_asset_id,
                "subaccount_id": subaccount_id,
                "complex_order_ids": complex_order_ids,
                "parent_river_order_id": parent_river_order_id,
                "unparented_only": unparented_only,
                "limit": limit,
                "offset": offset,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    ComplexOrderListResponse,
                    parse_obj_as(
                        type_=ComplexOrderListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def create_complex_order(
        self,
        *,
        subaccount_id: str,
        river_id: typing.Optional[int] = OMIT,
        generic_asset_id: typing.Optional[str] = OMIT,
        conditional_order_params: typing.Optional[ConditionalOrderCreate] = OMIT,
        iceberg_order_params: typing.Optional[IcebergOrderParams] = OMIT,
        peg_order_params: typing.Optional[PegOrderParams] = OMIT,
        smart_taker_order_params: typing.Optional[SmartTakerOrderParams] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ComplexOrderCreateResponse:
        """
        Create a new complex order (conditional or iceberg).

        Provide exactly one of `conditional_order_params` (TP/SL/STOP) or
        `iceberg_order_params`. The body shape determines the complex_order_type.

        Returns 202 Accepted with the persisted complex order in PENDING status,
        enqueued for activation by the appropriate consumer service.

        Parameters
        ----------
        subaccount_id : str
            Subaccount to create the order under

        river_id : typing.Optional[int]
            Instrument ID. Mutually exclusive with generic_asset_id.

        generic_asset_id : typing.Optional[str]
            Generic asset basket ID. Mutually exclusive with river_id.

        conditional_order_params : typing.Optional[ConditionalOrderCreate]
            Conditional order parameters (TP/SL/STOP)

        iceberg_order_params : typing.Optional[IcebergOrderParams]
            Iceberg order parameters

        peg_order_params : typing.Optional[PegOrderParams]
            Peg order parameters

        smart_taker_order_params : typing.Optional[SmartTakerOrderParams]
            Smart-taker order parameters

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ComplexOrderCreateResponse
            Successful Response

        Examples
        --------
        import asyncio

        from rivermarkets import AsyncRiverMarkets

        client = AsyncRiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.complex_orders.create_complex_order(
                subaccount_id="subaccount_id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/complex-orders",
            method="POST",
            json={
                "subaccount_id": subaccount_id,
                "river_id": river_id,
                "generic_asset_id": generic_asset_id,
                "conditional_order_params": convert_and_respect_annotation_metadata(
                    object_=conditional_order_params,
                    annotation=ConditionalOrderCreate,
                    direction="write",
                ),
                "iceberg_order_params": convert_and_respect_annotation_metadata(
                    object_=iceberg_order_params,
                    annotation=IcebergOrderParams,
                    direction="write",
                ),
                "peg_order_params": convert_and_respect_annotation_metadata(
                    object_=peg_order_params,
                    annotation=PegOrderParams,
                    direction="write",
                ),
                "smart_taker_order_params": convert_and_respect_annotation_metadata(
                    object_=smart_taker_order_params,
                    annotation=SmartTakerOrderParams,
                    direction="write",
                ),
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    ComplexOrderCreateResponse,
                    parse_obj_as(
                        type_=ComplexOrderCreateResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def cancel_all_complex_orders(
        self,
        *,
        subaccount_id: str,
        river_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CancelComplexOrderResponse:
        """
        Cancel all cancellable complex orders (conditional and iceberg) for a subaccount.

        Returns the list of complex_order_ids that were submitted for cancellation.

        Parameters
        ----------
        subaccount_id : str
            Subaccount to cancel all complex orders for

        river_ids : typing.Optional[typing.Sequence[int]]
            If set, only cancel cancellable complex orders for these instruments. Must be either omitted/null or a non-empty list.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CancelComplexOrderResponse
            Successful Response

        Examples
        --------
        import asyncio

        from rivermarkets import AsyncRiverMarkets

        client = AsyncRiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.complex_orders.cancel_all_complex_orders(
                subaccount_id="subaccount_id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/complex-orders/cancel-all",
            method="POST",
            json={
                "subaccount_id": subaccount_id,
                "river_ids": river_ids,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    CancelComplexOrderResponse,
                    parse_obj_as(
                        type_=CancelComplexOrderResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def get_complex_order(
        self,
        complex_order_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ComplexOrderResponse:
        """
        Get a single complex order by ID (conditional or iceberg).

        Parameters
        ----------
        complex_order_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ComplexOrderResponse
            Successful Response

        Examples
        --------
        import asyncio

        from rivermarkets import AsyncRiverMarkets

        client = AsyncRiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.complex_orders.get_complex_order(
                complex_order_id="complex_order_id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/complex-orders/{jsonable_encoder(complex_order_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    ComplexOrderResponse,
                    parse_obj_as(
                        type_=ComplexOrderResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def cancel_complex_order(
        self,
        complex_order_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CancelComplexOrderResponse:
        """
        Cancel a single complex order (conditional or iceberg).

        Returns 202 Accepted. Cancellation is processed asynchronously by the
        appropriate consumer service.

        Parameters
        ----------
        complex_order_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CancelComplexOrderResponse
            Successful Response

        Examples
        --------
        import asyncio

        from rivermarkets import AsyncRiverMarkets

        client = AsyncRiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.complex_orders.cancel_complex_order(
                complex_order_id="complex_order_id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/complex-orders/{jsonable_encoder(complex_order_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    CancelComplexOrderResponse,
                    parse_obj_as(
                        type_=CancelComplexOrderResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)
