# This file was auto-generated by Fern from our API Definition.

import typing
from ..core.client_wrapper import SyncClientWrapper
from .types.list_complex_orders_v1complex_orders_get_request_status import (
    ListComplexOrdersV1ComplexOrdersGetRequestStatus,
)
from ..core.request_options import RequestOptions
from ..types.complex_order_list_response import ComplexOrderListResponse
from ..core.pydantic_utilities import parse_obj_as
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.http_validation_error import HttpValidationError
from json.decoder import JSONDecodeError
from ..core.api_error import ApiError
from ..types.conditional_order_create import ConditionalOrderCreate
from ..types.complex_order_create_response import ComplexOrderCreateResponse
from ..core.serialization import convert_and_respect_annotation_metadata
from ..types.cancel_complex_order_response import CancelComplexOrderResponse
from ..types.complex_order_response import ComplexOrderResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.client_wrapper import AsyncClientWrapper

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ComplexOrdersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_complex_orders(
        self,
        *,
        complex_order_type: typing.Optional[str] = None,
        status: typing.Optional[
            ListComplexOrdersV1ComplexOrdersGetRequestStatus
        ] = None,
        river_id: typing.Optional[int] = None,
        custom_asset_id: typing.Optional[str] = None,
        subaccount_id: typing.Optional[str] = None,
        parent_river_order_id: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ComplexOrderListResponse:
        """
        List all complex orders with optional filters.

        Returns a paginated list of complex orders (conditional, TWAP, etc.) across all
        accessible subaccounts, ordered by `created_at` descending.

        **Filters:**
        All filters are optional and can be combined. Use `complex_order_type` to narrow
        to a specific type. If no `subaccount_id` is specified, returns orders from all
        subaccounts the user has access to.

        Parameters
        ----------
        complex_order_type : typing.Optional[str]

        status : typing.Optional[ListComplexOrdersV1ComplexOrdersGetRequestStatus]

        river_id : typing.Optional[int]

        custom_asset_id : typing.Optional[str]

        subaccount_id : typing.Optional[str]

        parent_river_order_id : typing.Optional[str]

        limit : typing.Optional[int]

        offset : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ComplexOrderListResponse
            Successful Response

        Examples
        --------
        from rivermarkets import RiverMarkets

        client = RiverMarkets(
            api_key="YOUR_API_KEY",
        )
        client.complex_orders.list_complex_orders()
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/complex-orders",
            method="GET",
            params={
                "complex_order_type": complex_order_type,
                "status": status,
                "river_id": river_id,
                "custom_asset_id": custom_asset_id,
                "subaccount_id": subaccount_id,
                "parent_river_order_id": parent_river_order_id,
                "limit": limit,
                "offset": offset,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    ComplexOrderListResponse,
                    parse_obj_as(
                        type_=ComplexOrderListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def create_complex_order(
        self,
        *,
        subaccount_id: str,
        river_id: typing.Optional[int] = OMIT,
        custom_asset_id: typing.Optional[str] = OMIT,
        conditional_order_params: typing.Optional[ConditionalOrderCreate] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ComplexOrderCreateResponse:
        """
        Create a new complex order.

        Currently supports conditional orders (TP, SL, STOP). The order is persisted
        immediately with `PENDING` status and queued for activation.

        **Conditional Order Types:**
        - `TP`: Take-profit attached to a parent order. Requires
          `parent_river_order_id` or `parent_complex_order_id`.
        - `SL`: Stop-loss attached to a parent order. Requires
          `parent_river_order_id` or `parent_complex_order_id`.
        - `STOP`: Standalone stop order triggered by market price.

        **Response:**
        Returns `202 Accepted` with the complex order in `PENDING` status.

        Parameters
        ----------
        subaccount_id : str
            Subaccount to create the order under

        river_id : typing.Optional[int]
            Instrument ID. Mutually exclusive with custom_asset_id.

        custom_asset_id : typing.Optional[str]
            Custom asset basket ID. Mutually exclusive with river_id.

        conditional_order_params : typing.Optional[ConditionalOrderCreate]
            Conditional order parameters

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ComplexOrderCreateResponse
            Successful Response

        Examples
        --------
        from rivermarkets import RiverMarkets

        client = RiverMarkets(
            api_key="YOUR_API_KEY",
        )
        client.complex_orders.create_complex_order(
            subaccount_id="subaccount_id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/complex-orders",
            method="POST",
            json={
                "subaccount_id": subaccount_id,
                "river_id": river_id,
                "custom_asset_id": custom_asset_id,
                "conditional_order_params": convert_and_respect_annotation_metadata(
                    object_=conditional_order_params,
                    annotation=ConditionalOrderCreate,
                    direction="write",
                ),
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    ComplexOrderCreateResponse,
                    parse_obj_as(
                        type_=ComplexOrderCreateResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def cancel_all_complex_orders(
        self,
        *,
        subaccount_id: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CancelComplexOrderResponse:
        """
        Cancel all complex orders for a subaccount.

        Returns count of orders being cancelled. Cancellation is processed asynchronously.

        Parameters
        ----------
        subaccount_id : str
            Subaccount to cancel all complex orders for

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CancelComplexOrderResponse
            Successful Response

        Examples
        --------
        from rivermarkets import RiverMarkets

        client = RiverMarkets(
            api_key="YOUR_API_KEY",
        )
        client.complex_orders.cancel_all_complex_orders(
            subaccount_id="subaccount_id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/complex-orders/cancel-all",
            method="POST",
            json={
                "subaccount_id": subaccount_id,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    CancelComplexOrderResponse,
                    parse_obj_as(
                        type_=CancelComplexOrderResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def get_complex_order(
        self,
        complex_order_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ComplexOrderResponse:
        """
        Get a single complex order by ID.

        Returns complete complex order details including trigger configuration
        and current status.

        Parameters
        ----------
        complex_order_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ComplexOrderResponse
            Successful Response

        Examples
        --------
        from rivermarkets import RiverMarkets

        client = RiverMarkets(
            api_key="YOUR_API_KEY",
        )
        client.complex_orders.get_complex_order(
            complex_order_id="complex_order_id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/complex-orders/{jsonable_encoder(complex_order_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    ComplexOrderResponse,
                    parse_obj_as(
                        type_=ComplexOrderResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def cancel_complex_order(
        self,
        complex_order_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CancelComplexOrderResponse:
        """
        Cancel a complex order.

        Request cancellation of a complex order.
        Returns 202 Accepted with the current complex order state —
        cancellation is processed asynchronously.

        Parameters
        ----------
        complex_order_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CancelComplexOrderResponse
            Successful Response

        Examples
        --------
        from rivermarkets import RiverMarkets

        client = RiverMarkets(
            api_key="YOUR_API_KEY",
        )
        client.complex_orders.cancel_complex_order(
            complex_order_id="complex_order_id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/complex-orders/{jsonable_encoder(complex_order_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    CancelComplexOrderResponse,
                    parse_obj_as(
                        type_=CancelComplexOrderResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)


class AsyncComplexOrdersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_complex_orders(
        self,
        *,
        complex_order_type: typing.Optional[str] = None,
        status: typing.Optional[
            ListComplexOrdersV1ComplexOrdersGetRequestStatus
        ] = None,
        river_id: typing.Optional[int] = None,
        custom_asset_id: typing.Optional[str] = None,
        subaccount_id: typing.Optional[str] = None,
        parent_river_order_id: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ComplexOrderListResponse:
        """
        List all complex orders with optional filters.

        Returns a paginated list of complex orders (conditional, TWAP, etc.) across all
        accessible subaccounts, ordered by `created_at` descending.

        **Filters:**
        All filters are optional and can be combined. Use `complex_order_type` to narrow
        to a specific type. If no `subaccount_id` is specified, returns orders from all
        subaccounts the user has access to.

        Parameters
        ----------
        complex_order_type : typing.Optional[str]

        status : typing.Optional[ListComplexOrdersV1ComplexOrdersGetRequestStatus]

        river_id : typing.Optional[int]

        custom_asset_id : typing.Optional[str]

        subaccount_id : typing.Optional[str]

        parent_river_order_id : typing.Optional[str]

        limit : typing.Optional[int]

        offset : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ComplexOrderListResponse
            Successful Response

        Examples
        --------
        import asyncio

        from rivermarkets import AsyncRiverMarkets

        client = AsyncRiverMarkets(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.complex_orders.list_complex_orders()


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/complex-orders",
            method="GET",
            params={
                "complex_order_type": complex_order_type,
                "status": status,
                "river_id": river_id,
                "custom_asset_id": custom_asset_id,
                "subaccount_id": subaccount_id,
                "parent_river_order_id": parent_river_order_id,
                "limit": limit,
                "offset": offset,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    ComplexOrderListResponse,
                    parse_obj_as(
                        type_=ComplexOrderListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def create_complex_order(
        self,
        *,
        subaccount_id: str,
        river_id: typing.Optional[int] = OMIT,
        custom_asset_id: typing.Optional[str] = OMIT,
        conditional_order_params: typing.Optional[ConditionalOrderCreate] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ComplexOrderCreateResponse:
        """
        Create a new complex order.

        Currently supports conditional orders (TP, SL, STOP). The order is persisted
        immediately with `PENDING` status and queued for activation.

        **Conditional Order Types:**
        - `TP`: Take-profit attached to a parent order. Requires
          `parent_river_order_id` or `parent_complex_order_id`.
        - `SL`: Stop-loss attached to a parent order. Requires
          `parent_river_order_id` or `parent_complex_order_id`.
        - `STOP`: Standalone stop order triggered by market price.

        **Response:**
        Returns `202 Accepted` with the complex order in `PENDING` status.

        Parameters
        ----------
        subaccount_id : str
            Subaccount to create the order under

        river_id : typing.Optional[int]
            Instrument ID. Mutually exclusive with custom_asset_id.

        custom_asset_id : typing.Optional[str]
            Custom asset basket ID. Mutually exclusive with river_id.

        conditional_order_params : typing.Optional[ConditionalOrderCreate]
            Conditional order parameters

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ComplexOrderCreateResponse
            Successful Response

        Examples
        --------
        import asyncio

        from rivermarkets import AsyncRiverMarkets

        client = AsyncRiverMarkets(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.complex_orders.create_complex_order(
                subaccount_id="subaccount_id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/complex-orders",
            method="POST",
            json={
                "subaccount_id": subaccount_id,
                "river_id": river_id,
                "custom_asset_id": custom_asset_id,
                "conditional_order_params": convert_and_respect_annotation_metadata(
                    object_=conditional_order_params,
                    annotation=ConditionalOrderCreate,
                    direction="write",
                ),
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    ComplexOrderCreateResponse,
                    parse_obj_as(
                        type_=ComplexOrderCreateResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def cancel_all_complex_orders(
        self,
        *,
        subaccount_id: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CancelComplexOrderResponse:
        """
        Cancel all complex orders for a subaccount.

        Returns count of orders being cancelled. Cancellation is processed asynchronously.

        Parameters
        ----------
        subaccount_id : str
            Subaccount to cancel all complex orders for

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CancelComplexOrderResponse
            Successful Response

        Examples
        --------
        import asyncio

        from rivermarkets import AsyncRiverMarkets

        client = AsyncRiverMarkets(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.complex_orders.cancel_all_complex_orders(
                subaccount_id="subaccount_id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/complex-orders/cancel-all",
            method="POST",
            json={
                "subaccount_id": subaccount_id,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    CancelComplexOrderResponse,
                    parse_obj_as(
                        type_=CancelComplexOrderResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def get_complex_order(
        self,
        complex_order_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ComplexOrderResponse:
        """
        Get a single complex order by ID.

        Returns complete complex order details including trigger configuration
        and current status.

        Parameters
        ----------
        complex_order_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ComplexOrderResponse
            Successful Response

        Examples
        --------
        import asyncio

        from rivermarkets import AsyncRiverMarkets

        client = AsyncRiverMarkets(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.complex_orders.get_complex_order(
                complex_order_id="complex_order_id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/complex-orders/{jsonable_encoder(complex_order_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    ComplexOrderResponse,
                    parse_obj_as(
                        type_=ComplexOrderResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def cancel_complex_order(
        self,
        complex_order_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CancelComplexOrderResponse:
        """
        Cancel a complex order.

        Request cancellation of a complex order.
        Returns 202 Accepted with the current complex order state —
        cancellation is processed asynchronously.

        Parameters
        ----------
        complex_order_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CancelComplexOrderResponse
            Successful Response

        Examples
        --------
        import asyncio

        from rivermarkets import AsyncRiverMarkets

        client = AsyncRiverMarkets(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.complex_orders.cancel_complex_order(
                complex_order_id="complex_order_id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/complex-orders/{jsonable_encoder(complex_order_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    CancelComplexOrderResponse,
                    parse_obj_as(
                        type_=CancelComplexOrderResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)
