# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.fee_schedule_lookup_response import FeeScheduleLookupResponse
from ..types.http_validation_error import HttpValidationError

OMIT = typing.cast(typing.Any, ...)


class FeesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def lookup_fee_schedules(
        self,
        *,
        river_ids: typing.Sequence[int],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FeeScheduleLookupResponse:
        """Return normalized fee schedules for up to 1,000 instruments."""
        response = self._client_wrapper.httpx_client.request(
            "v1/fees/schedules/lookup",
            method="POST",
            json={
                "river_ids": convert_and_respect_annotation_metadata(
                    object_=river_ids,
                    annotation=typing.Sequence[int],
                    direction="write",
                )
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= response.status_code < 300:
                return typing.cast(
                    FeeScheduleLookupResponse,
                    parse_obj_as(
                        type_=FeeScheduleLookupResponse,  # type: ignore
                        object_=response.json(),
                    ),
                )
            if response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=response.json(),
                        ),
                    )
                )
            response_json = response.json()
        except JSONDecodeError:
            raise ApiError(status_code=response.status_code, body=response.text)
        raise ApiError(status_code=response.status_code, body=response_json)


class AsyncFeesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def lookup_fee_schedules(
        self,
        *,
        river_ids: typing.Sequence[int],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FeeScheduleLookupResponse:
        """Return normalized fee schedules for up to 1,000 instruments."""
        response = await self._client_wrapper.httpx_client.request(
            "v1/fees/schedules/lookup",
            method="POST",
            json={
                "river_ids": convert_and_respect_annotation_metadata(
                    object_=river_ids,
                    annotation=typing.Sequence[int],
                    direction="write",
                )
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= response.status_code < 300:
                return typing.cast(
                    FeeScheduleLookupResponse,
                    parse_obj_as(
                        type_=FeeScheduleLookupResponse,  # type: ignore
                        object_=response.json(),
                    ),
                )
            if response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=response.json(),
                        ),
                    )
                )
            response_json = response.json()
        except JSONDecodeError:
            raise ApiError(status_code=response.status_code, body=response.text)
        raise ApiError(status_code=response.status_code, body=response_json)
