# This file was auto-generated by Fern from our API Definition.
# Hand-edited post-regen by fern/postprocess.py to add Ed25519 signing,
# WebSocket realtime support, and environment handling. Re-running
# `fern generate` and `python3 fern/postprocess.py` is idempotent.

import typing
from .environment import RiverMarketsEnvironment
import httpx
from .auth import RiverMarketsSigner
from .realtime import RealtimeClient
from .core.client_wrapper import SyncClientWrapper
from .complex_orders.client import ComplexOrdersClient
from .fills.client import FillsClient
from .generic_assets.client import GenericAssetsClient
from .markets.client import MarketsClient
from .orderbooks.client import OrderbooksClient
from .orders.client import OrdersClient
from .positions.client import PositionsClient
from .prices.client import PricesClient
from .subaccounts.client import SubaccountsClient
from .core.client_wrapper import AsyncClientWrapper
from .complex_orders.client import AsyncComplexOrdersClient
from .fills.client import AsyncFillsClient
from .generic_assets.client import AsyncGenericAssetsClient
from .markets.client import AsyncMarketsClient
from .orderbooks.client import AsyncOrderbooksClient
from .orders.client import AsyncOrdersClient
from .positions.client import AsyncPositionsClient
from .prices.client import AsyncPricesClient
from .subaccounts.client import AsyncSubaccountsClient


class RiverMarkets:
    """
    Sync client for the River Markets REST API.

    Parameters
    ----------
    key_id : str
        UUID of your API key (from Settings → API Keys).

    private_key : str
        Base64-encoded Ed25519 private key shown once at key creation.

    base_url : typing.Optional[str]
        Override for the API base URL. Defaults to environment.value.

    environment : RiverMarketsEnvironment
        Defaults to RiverMarketsEnvironment.DEFAULT.

    timeout : typing.Optional[float]
        Per-request timeout in seconds. Default 60.

    follow_redirects : typing.Optional[bool]
        Default True. Ignored if httpx_client is provided.

    httpx_client : typing.Optional[httpx.Client]
        If provided, the signer is attached to its .auth attribute.

    Examples
    --------
    from rivermarkets import RiverMarkets

    client = RiverMarkets(
        key_id="YOUR_KEY_ID",
        private_key="YOUR_BASE64_PRIVATE_KEY",
    )
    """

    def __init__(
        self,
        *,
        key_id: str,
        private_key: str,
        base_url: typing.Optional[str] = None,
        environment: RiverMarketsEnvironment = RiverMarketsEnvironment.DEFAULT,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.Client] = None,
    ):
        _defaulted_timeout = (
            timeout if timeout is not None else 60 if httpx_client is None else None
        )
        signer = RiverMarketsSigner(key_id=key_id, private_key=private_key)
        if httpx_client is not None:
            httpx_client.auth = signer
            client = httpx_client
        elif follow_redirects is not None:
            client = httpx.Client(
                timeout=_defaulted_timeout,
                follow_redirects=follow_redirects,
                auth=signer,
            )
        else:
            client = httpx.Client(timeout=_defaulted_timeout, auth=signer)
        self._client_wrapper = SyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            httpx_client=client,
            timeout=_defaulted_timeout,
        )
        self.complex_orders = ComplexOrdersClient(client_wrapper=self._client_wrapper)
        self.fills = FillsClient(client_wrapper=self._client_wrapper)
        self.generic_assets = GenericAssetsClient(client_wrapper=self._client_wrapper)
        self.markets = MarketsClient(client_wrapper=self._client_wrapper)
        self.orderbooks = OrderbooksClient(client_wrapper=self._client_wrapper)
        self.orders = OrdersClient(client_wrapper=self._client_wrapper)
        self.positions = PositionsClient(client_wrapper=self._client_wrapper)
        self.prices = PricesClient(client_wrapper=self._client_wrapper)
        self.subaccounts = SubaccountsClient(client_wrapper=self._client_wrapper)


class AsyncRiverMarkets:
    """
    Async client for the River Markets REST API + realtime WebSockets.

    Parameters mirror :class:`RiverMarkets`. The ``.realtime`` attribute
    exposes the async-only WebSocket client.

    Examples
    --------
    from rivermarkets import AsyncRiverMarkets

    client = AsyncRiverMarkets(
        key_id="YOUR_KEY_ID",
        private_key="YOUR_BASE64_PRIVATE_KEY",
    )

    async with client.realtime.orderbooks([12345]) as stream:
        async for msg in stream:
            ...
    """

    def __init__(
        self,
        *,
        key_id: str,
        private_key: str,
        base_url: typing.Optional[str] = None,
        environment: RiverMarketsEnvironment = RiverMarketsEnvironment.DEFAULT,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.AsyncClient] = None,
    ):
        _defaulted_timeout = (
            timeout if timeout is not None else 60 if httpx_client is None else None
        )
        signer = RiverMarketsSigner(key_id=key_id, private_key=private_key)
        if httpx_client is not None:
            httpx_client.auth = signer
            client = httpx_client
        elif follow_redirects is not None:
            client = httpx.AsyncClient(
                timeout=_defaulted_timeout,
                follow_redirects=follow_redirects,
                auth=signer,
            )
        else:
            client = httpx.AsyncClient(timeout=_defaulted_timeout, auth=signer)
        resolved_base_url = _get_base_url(base_url=base_url, environment=environment)
        self._client_wrapper = AsyncClientWrapper(
            base_url=resolved_base_url,
            httpx_client=client,
            timeout=_defaulted_timeout,
        )
        ws_base_url = resolved_base_url.replace("https://", "wss://", 1).replace(
            "http://", "ws://", 1
        )
        self.realtime = RealtimeClient(
            key_id=key_id,
            private_key=private_key,
            base_url=ws_base_url,
        )
        self.complex_orders = AsyncComplexOrdersClient(client_wrapper=self._client_wrapper)
        self.fills = AsyncFillsClient(client_wrapper=self._client_wrapper)
        self.generic_assets = AsyncGenericAssetsClient(client_wrapper=self._client_wrapper)
        self.markets = AsyncMarketsClient(client_wrapper=self._client_wrapper)
        self.orderbooks = AsyncOrderbooksClient(client_wrapper=self._client_wrapper)
        self.orders = AsyncOrdersClient(client_wrapper=self._client_wrapper)
        self.positions = AsyncPositionsClient(client_wrapper=self._client_wrapper)
        self.prices = AsyncPricesClient(client_wrapper=self._client_wrapper)
        self.subaccounts = AsyncSubaccountsClient(client_wrapper=self._client_wrapper)


def _get_base_url(
    *, base_url: typing.Optional[str] = None, environment: RiverMarketsEnvironment
) -> str:
    if base_url is not None:
        return base_url
    elif environment is not None:
        return environment.value
    else:
        raise Exception(
            "Please pass in either base_url or environment to construct the client"
        )
