# This file was auto-generated by Fern from our API Definition.

from ..core.client_wrapper import SyncClientWrapper
import typing
from ..core.request_options import RequestOptions
from ..types.user_position_list_response import UserPositionListResponse
from ..core.pydantic_utilities import parse_obj_as
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.http_validation_error import HttpValidationError
from json.decoder import JSONDecodeError
from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper


class PositionsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def get_positions(
        self,
        *,
        subaccount_id: typing.Optional[str] = None,
        include_closed: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UserPositionListResponse:
        """
        Fetch positions for user's subaccounts.

        Returns positions grouped by subaccount. Optionally filter to a specific subaccount.
        By default, only positions in open markets are returned.

        Parameters
        ----------
        subaccount_id : typing.Optional[str]
            Filter by specific subaccount

        include_closed : typing.Optional[bool]
            Include positions in closed markets

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UserPositionListResponse
            Successful Response

        Examples
        --------
        from rivermarkets import RiverMarkets

        client = RiverMarkets(
            api_key="YOUR_API_KEY",
        )
        client.positions.get_positions()
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/positions",
            method="GET",
            params={
                "subaccount_id": subaccount_id,
                "include_closed": include_closed,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    UserPositionListResponse,
                    parse_obj_as(
                        type_=UserPositionListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)


class AsyncPositionsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def get_positions(
        self,
        *,
        subaccount_id: typing.Optional[str] = None,
        include_closed: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UserPositionListResponse:
        """
        Fetch positions for user's subaccounts.

        Returns positions grouped by subaccount. Optionally filter to a specific subaccount.
        By default, only positions in open markets are returned.

        Parameters
        ----------
        subaccount_id : typing.Optional[str]
            Filter by specific subaccount

        include_closed : typing.Optional[bool]
            Include positions in closed markets

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UserPositionListResponse
            Successful Response

        Examples
        --------
        import asyncio

        from rivermarkets import AsyncRiverMarkets

        client = AsyncRiverMarkets(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.positions.get_positions()


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/positions",
            method="GET",
            params={
                "subaccount_id": subaccount_id,
                "include_closed": include_closed,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    UserPositionListResponse,
                    parse_obj_as(
                        type_=UserPositionListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)
