# This file was auto-generated by Fern from our API Definition.

import typing
from ..core.client_wrapper import SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.generic_asset_list_response import GenericAssetListResponse
from ..core.pydantic_utilities import parse_obj_as
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.http_validation_error import HttpValidationError
from json.decoder import JSONDecodeError
from ..core.api_error import ApiError
from ..types.generic_asset_detail_response import GenericAssetDetailResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..types.generic_asset_response import GenericAssetResponse
from ..core.client_wrapper import AsyncClientWrapper

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class GenericAssetsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_generic_assets(
        self,
        *,
        category: typing.Optional[typing.Sequence[str]] = None,
        subcategory: typing.Optional[str] = None,
        owner: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GenericAssetListResponse:
        """
        List generic assets visible to the caller (their own + platform-curated approved).

        Sorted by resolves_at (soonest first), then name.

        Parameters
        ----------
        category : typing.Optional[typing.Sequence[str]]
            Filter by category. Repeat to filter to multiple categories.

        subcategory : typing.Optional[str]
            Filter by subcategory

        owner : typing.Optional[str]
            'me' for own baskets only, 'platform' for public only

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GenericAssetListResponse
            Successful Response

        Examples
        --------
        from rivermarkets import RiverMarkets

        client = RiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )
        client.generic_assets.list_generic_assets()
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/generic-assets",
            method="GET",
            params={
                "category": category,
                "subcategory": subcategory,
                "owner": owner,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    GenericAssetListResponse,
                    parse_obj_as(
                        type_=GenericAssetListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def create_generic_asset(
        self,
        *,
        subaccount_id: str,
        name: str,
        description: typing.Optional[str] = OMIT,
        river_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GenericAssetDetailResponse:
        """
        Create a new user-owned generic asset (basket).

        Parameters
        ----------
        subaccount_id : str

        name : str

        description : typing.Optional[str]

        river_ids : typing.Optional[typing.Sequence[int]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GenericAssetDetailResponse
            Successful Response

        Examples
        --------
        from rivermarkets import RiverMarkets

        client = RiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )
        client.generic_assets.create_generic_asset(
            subaccount_id="subaccount_id",
            name="name",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/generic-assets",
            method="POST",
            json={
                "subaccount_id": subaccount_id,
                "name": name,
                "description": description,
                "river_ids": river_ids,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    GenericAssetDetailResponse,
                    parse_obj_as(
                        type_=GenericAssetDetailResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def get_generic_asset(
        self,
        generic_asset_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GenericAssetDetailResponse:
        """
        Fetch a single generic asset (own or public-approved) with its resolved member markets.

        Parameters
        ----------
        generic_asset_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GenericAssetDetailResponse
            Successful Response

        Examples
        --------
        from rivermarkets import RiverMarkets

        client = RiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )
        client.generic_assets.get_generic_asset(
            generic_asset_id="generic_asset_id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/generic-assets/{jsonable_encoder(generic_asset_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    GenericAssetDetailResponse,
                    parse_obj_as(
                        type_=GenericAssetDetailResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def delete_generic_asset(
        self,
        generic_asset_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Delete a user-owned generic asset (cascades to members).

        Parameters
        ----------
        generic_asset_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from rivermarkets import RiverMarkets

        client = RiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )
        client.generic_assets.delete_generic_asset(
            generic_asset_id="generic_asset_id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/generic-assets/{jsonable_encoder(generic_asset_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def update_generic_asset(
        self,
        generic_asset_id: str,
        *,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GenericAssetResponse:
        """
        Update a user-owned generic asset's name or description. Platform-curated assets cannot be edited via this route.

        Parameters
        ----------
        generic_asset_id : str

        name : typing.Optional[str]

        description : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GenericAssetResponse
            Successful Response

        Examples
        --------
        from rivermarkets import RiverMarkets

        client = RiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )
        client.generic_assets.update_generic_asset(
            generic_asset_id="generic_asset_id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/generic-assets/{jsonable_encoder(generic_asset_id)}",
            method="PATCH",
            json={
                "name": name,
                "description": description,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    GenericAssetResponse,
                    parse_obj_as(
                        type_=GenericAssetResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def add_generic_asset_members(
        self,
        generic_asset_id: str,
        *,
        river_ids: typing.Sequence[int],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Add river_ids to a user-owned generic asset.

        Parameters
        ----------
        generic_asset_id : str

        river_ids : typing.Sequence[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from rivermarkets import RiverMarkets

        client = RiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )
        client.generic_assets.add_generic_asset_members(
            generic_asset_id="generic_asset_id",
            river_ids=[1],
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/generic-assets/{jsonable_encoder(generic_asset_id)}/members",
            method="POST",
            json={
                "river_ids": river_ids,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def remove_generic_asset_members(
        self,
        generic_asset_id: str,
        *,
        river_ids: typing.Sequence[int],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Remove river_ids from a user-owned generic asset.

        Parameters
        ----------
        generic_asset_id : str

        river_ids : typing.Sequence[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from rivermarkets import RiverMarkets

        client = RiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )
        client.generic_assets.remove_generic_asset_members(
            generic_asset_id="generic_asset_id",
            river_ids=[1],
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/generic-assets/{jsonable_encoder(generic_asset_id)}/members",
            method="DELETE",
            json={
                "river_ids": river_ids,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)


class AsyncGenericAssetsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_generic_assets(
        self,
        *,
        category: typing.Optional[typing.Sequence[str]] = None,
        subcategory: typing.Optional[str] = None,
        owner: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GenericAssetListResponse:
        """
        List generic assets visible to the caller (their own + platform-curated approved).

        Sorted by resolves_at (soonest first), then name.

        Parameters
        ----------
        category : typing.Optional[typing.Sequence[str]]
            Filter by category. Repeat to filter to multiple categories.

        subcategory : typing.Optional[str]
            Filter by subcategory

        owner : typing.Optional[str]
            'me' for own baskets only, 'platform' for public only

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GenericAssetListResponse
            Successful Response

        Examples
        --------
        import asyncio

        from rivermarkets import AsyncRiverMarkets

        client = AsyncRiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.generic_assets.list_generic_assets()


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/generic-assets",
            method="GET",
            params={
                "category": category,
                "subcategory": subcategory,
                "owner": owner,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    GenericAssetListResponse,
                    parse_obj_as(
                        type_=GenericAssetListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def create_generic_asset(
        self,
        *,
        subaccount_id: str,
        name: str,
        description: typing.Optional[str] = OMIT,
        river_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GenericAssetDetailResponse:
        """
        Create a new user-owned generic asset (basket).

        Parameters
        ----------
        subaccount_id : str

        name : str

        description : typing.Optional[str]

        river_ids : typing.Optional[typing.Sequence[int]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GenericAssetDetailResponse
            Successful Response

        Examples
        --------
        import asyncio

        from rivermarkets import AsyncRiverMarkets

        client = AsyncRiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.generic_assets.create_generic_asset(
                subaccount_id="subaccount_id",
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/generic-assets",
            method="POST",
            json={
                "subaccount_id": subaccount_id,
                "name": name,
                "description": description,
                "river_ids": river_ids,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    GenericAssetDetailResponse,
                    parse_obj_as(
                        type_=GenericAssetDetailResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def get_generic_asset(
        self,
        generic_asset_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GenericAssetDetailResponse:
        """
        Fetch a single generic asset (own or public-approved) with its resolved member markets.

        Parameters
        ----------
        generic_asset_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GenericAssetDetailResponse
            Successful Response

        Examples
        --------
        import asyncio

        from rivermarkets import AsyncRiverMarkets

        client = AsyncRiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.generic_assets.get_generic_asset(
                generic_asset_id="generic_asset_id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/generic-assets/{jsonable_encoder(generic_asset_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    GenericAssetDetailResponse,
                    parse_obj_as(
                        type_=GenericAssetDetailResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def delete_generic_asset(
        self,
        generic_asset_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Delete a user-owned generic asset (cascades to members).

        Parameters
        ----------
        generic_asset_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from rivermarkets import AsyncRiverMarkets

        client = AsyncRiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.generic_assets.delete_generic_asset(
                generic_asset_id="generic_asset_id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/generic-assets/{jsonable_encoder(generic_asset_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def update_generic_asset(
        self,
        generic_asset_id: str,
        *,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GenericAssetResponse:
        """
        Update a user-owned generic asset's name or description. Platform-curated assets cannot be edited via this route.

        Parameters
        ----------
        generic_asset_id : str

        name : typing.Optional[str]

        description : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GenericAssetResponse
            Successful Response

        Examples
        --------
        import asyncio

        from rivermarkets import AsyncRiverMarkets

        client = AsyncRiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.generic_assets.update_generic_asset(
                generic_asset_id="generic_asset_id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/generic-assets/{jsonable_encoder(generic_asset_id)}",
            method="PATCH",
            json={
                "name": name,
                "description": description,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    GenericAssetResponse,
                    parse_obj_as(
                        type_=GenericAssetResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def add_generic_asset_members(
        self,
        generic_asset_id: str,
        *,
        river_ids: typing.Sequence[int],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Add river_ids to a user-owned generic asset.

        Parameters
        ----------
        generic_asset_id : str

        river_ids : typing.Sequence[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from rivermarkets import AsyncRiverMarkets

        client = AsyncRiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.generic_assets.add_generic_asset_members(
                generic_asset_id="generic_asset_id",
                river_ids=[1],
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/generic-assets/{jsonable_encoder(generic_asset_id)}/members",
            method="POST",
            json={
                "river_ids": river_ids,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def remove_generic_asset_members(
        self,
        generic_asset_id: str,
        *,
        river_ids: typing.Sequence[int],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Remove river_ids from a user-owned generic asset.

        Parameters
        ----------
        generic_asset_id : str

        river_ids : typing.Sequence[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from rivermarkets import AsyncRiverMarkets

        client = AsyncRiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.generic_assets.remove_generic_asset_members(
                generic_asset_id="generic_asset_id",
                river_ids=[1],
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/generic-assets/{jsonable_encoder(generic_asset_id)}/members",
            method="DELETE",
            json={
                "river_ids": river_ids,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)
