"""Re-apply hand-edits on top of a fresh ``fern generate``.

Idempotent — safe to run multiple times. Invoked by ``fern/regen.sh`` or
directly via ``python3 fern/postprocess.py``.

What this does (and why each piece exists):

1. Copies ``fern/templates/`` into ``rivermarkets/``. Fern wipes the output
   tree on every regen — anything hand-written must live in ``fern/templates/``
   to survive. Currently: ``auth.py``, ``environment.py``, ``realtime/``.

2. Rewrites ``rivermarkets/client.py`` from a single template, splicing in
   the subclient list extracted from the freshly-generated file. This adds
   Ed25519 signing, environment handling, and attaches ``RealtimeClient`` to
   the async variant.

3. Patches ``rivermarkets/__init__.py`` to re-export the hand-written
   modules. Idempotent — skips entries already present.

4. Patches ``rivermarkets/core/client_wrapper.py`` with a warning comment
   explaining the file is sensitive to the auth flow.

5. Removes ``rivermarkets/tests/`` — Fern's Python generator emits sample
   tests we don't want in the published SDK.
"""

from __future__ import annotations

import re
import shutil
from pathlib import Path
from typing import List, Tuple

HERE = Path(__file__).parent
ROOT = HERE.parent
RM = ROOT / "rivermarkets"
TEMPLATES = HERE / "templates"

CLIENT_PY = RM / "client.py"
INIT_PY = RM / "__init__.py"
WRAPPER_PY = RM / "core" / "client_wrapper.py"
TESTS_DIR = RM / "tests"


# ---------------------------------------------------------------------------
# 1. Copy hand-written files into the generated tree.
# ---------------------------------------------------------------------------


def restore_templates() -> None:
    """Copy every file under ``fern/templates/`` into ``rivermarkets/``."""
    for src in TEMPLATES.rglob("*"):
        if src.is_dir():
            continue
        dst = RM / src.relative_to(TEMPLATES)
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)


# ---------------------------------------------------------------------------
# 2. Rewrite client.py with auth + realtime wiring.
# ---------------------------------------------------------------------------

SUBCLIENT_IMPORT_RE = re.compile(
    r"^from \.(\w+)\.client import (Async)?(\w+)Client$", re.MULTILINE
)


def _extract_subclients(generated: str) -> Tuple[List[Tuple[str, str]], List[Tuple[str, str]]]:
    """Return ``(sync, async_)`` lists of ``(module_name, ClassName)`` tuples."""
    sync: List[Tuple[str, str]] = []
    async_: List[Tuple[str, str]] = []
    for m in SUBCLIENT_IMPORT_RE.finditer(generated):
        mod, async_marker, base = m.group(1), m.group(2), m.group(3)
        cls = (async_marker or "") + base + "Client"
        if async_marker == "Async":
            async_.append((mod, cls))
        else:
            sync.append((mod, cls))
    return sync, async_


def _render_subclient_imports(
    sync: List[Tuple[str, str]], async_: List[Tuple[str, str]]
) -> str:
    lines = [f"from .{mod}.client import {cls}" for mod, cls in sync]
    lines.append("from .core.client_wrapper import AsyncClientWrapper")
    lines.extend(f"from .{mod}.client import {cls}" for mod, cls in async_)
    return "\n".join(lines)


def _render_attr_assignments(subs: List[Tuple[str, str]]) -> str:
    return "\n".join(
        f"        self.{mod} = {cls}(client_wrapper=self._client_wrapper)"
        for mod, cls in subs
    )


CLIENT_PY_TEMPLATE = '''\
# This file was auto-generated by Fern from our API Definition.
# Hand-edited post-regen by fern/postprocess.py to add Ed25519 signing,
# WebSocket realtime support, and environment handling. Re-running
# `fern generate` and `python3 fern/postprocess.py` is idempotent.

import typing
from .environment import RiverMarketsEnvironment
import httpx
from .auth import RiverMarketsSigner
from .realtime import RealtimeClient
from .core.client_wrapper import SyncClientWrapper
{sync_imports}


class RiverMarkets:
    """
    Sync client for the River Markets REST API.

    Parameters
    ----------
    key_id : str
        UUID of your API key (from Settings → API Keys).

    private_key : str
        Base64-encoded Ed25519 private key shown once at key creation.

    base_url : typing.Optional[str]
        Override for the API base URL. Defaults to environment.value.

    environment : RiverMarketsEnvironment
        Defaults to RiverMarketsEnvironment.DEFAULT.

    timeout : typing.Optional[float]
        Per-request timeout in seconds. Default 60.

    follow_redirects : typing.Optional[bool]
        Default True. Ignored if httpx_client is provided.

    httpx_client : typing.Optional[httpx.Client]
        If provided, the signer is attached to its .auth attribute.

    Examples
    --------
    from rivermarkets import RiverMarkets

    client = RiverMarkets(
        key_id="YOUR_KEY_ID",
        private_key="YOUR_BASE64_PRIVATE_KEY",
    )
    """

    def __init__(
        self,
        *,
        key_id: str,
        private_key: str,
        base_url: typing.Optional[str] = None,
        environment: RiverMarketsEnvironment = RiverMarketsEnvironment.DEFAULT,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.Client] = None,
    ):
        _defaulted_timeout = (
            timeout if timeout is not None else 60 if httpx_client is None else None
        )
        signer = RiverMarketsSigner(key_id=key_id, private_key=private_key)
        if httpx_client is not None:
            httpx_client.auth = signer
            client = httpx_client
        elif follow_redirects is not None:
            client = httpx.Client(
                timeout=_defaulted_timeout,
                follow_redirects=follow_redirects,
                auth=signer,
            )
        else:
            client = httpx.Client(timeout=_defaulted_timeout, auth=signer)
        self._client_wrapper = SyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            httpx_client=client,
            timeout=_defaulted_timeout,
        )
{sync_attrs}


class AsyncRiverMarkets:
    """
    Async client for the River Markets REST API + realtime WebSockets.

    Parameters mirror :class:`RiverMarkets`. The ``.realtime`` attribute
    exposes the async-only WebSocket client.

    Examples
    --------
    from rivermarkets import AsyncRiverMarkets

    client = AsyncRiverMarkets(
        key_id="YOUR_KEY_ID",
        private_key="YOUR_BASE64_PRIVATE_KEY",
    )

    async with client.realtime.orderbooks([12345]) as stream:
        async for msg in stream:
            ...
    """

    def __init__(
        self,
        *,
        key_id: str,
        private_key: str,
        base_url: typing.Optional[str] = None,
        environment: RiverMarketsEnvironment = RiverMarketsEnvironment.DEFAULT,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.AsyncClient] = None,
    ):
        _defaulted_timeout = (
            timeout if timeout is not None else 60 if httpx_client is None else None
        )
        signer = RiverMarketsSigner(key_id=key_id, private_key=private_key)
        if httpx_client is not None:
            httpx_client.auth = signer
            client = httpx_client
        elif follow_redirects is not None:
            client = httpx.AsyncClient(
                timeout=_defaulted_timeout,
                follow_redirects=follow_redirects,
                auth=signer,
            )
        else:
            client = httpx.AsyncClient(timeout=_defaulted_timeout, auth=signer)
        resolved_base_url = _get_base_url(base_url=base_url, environment=environment)
        self._client_wrapper = AsyncClientWrapper(
            base_url=resolved_base_url,
            httpx_client=client,
            timeout=_defaulted_timeout,
        )
        ws_base_url = resolved_base_url.replace("https://", "wss://", 1).replace(
            "http://", "ws://", 1
        )
        self.realtime = RealtimeClient(
            key_id=key_id,
            private_key=private_key,
            base_url=ws_base_url,
        )
{async_attrs}


def _get_base_url(
    *, base_url: typing.Optional[str] = None, environment: RiverMarketsEnvironment
) -> str:
    if base_url is not None:
        return base_url
    elif environment is not None:
        return environment.value
    else:
        raise Exception(
            "Please pass in either base_url or environment to construct the client"
        )
'''


def patch_client_py() -> None:
    if not CLIENT_PY.exists():
        raise SystemExit(f"missing {CLIENT_PY} — did `fern generate` run?")
    generated = CLIENT_PY.read_text()
    sync, async_ = _extract_subclients(generated)
    if not sync or not async_:
        raise SystemExit(
            "couldn't extract subclient list from client.py — "
            "the generator's output format may have changed"
        )
    rendered = CLIENT_PY_TEMPLATE.format(
        sync_imports=_render_subclient_imports(sync, async_),
        sync_attrs=_render_attr_assignments(sync),
        async_attrs=_render_attr_assignments(async_),
    )
    CLIENT_PY.write_text(rendered)


# ---------------------------------------------------------------------------
# 3. __init__.py — add re-exports for hand-written modules.
# ---------------------------------------------------------------------------

INIT_EXTRA_IMPORTS = [
    "from .auth import RiverMarketsSigner",
    "from .environment import RiverMarketsEnvironment",
    "from .realtime import RealtimeClient",
]
INIT_EXTRA_ALL = ["RealtimeClient", "RiverMarketsEnvironment", "RiverMarketsSigner"]


def patch_init_py() -> None:
    text = INIT_PY.read_text()
    lines = text.splitlines()

    anchor_idx = next(
        (i for i, line in enumerate(lines) if line.startswith("from .client import")),
        None,
    )
    if anchor_idx is None:
        raise SystemExit("couldn't find `from .client import` anchor in __init__.py")
    for imp in INIT_EXTRA_IMPORTS:
        if imp not in lines:
            lines.insert(anchor_idx, imp)
            anchor_idx += 1

    for entry in INIT_EXTRA_ALL:
        quoted = f'    "{entry}",'
        if quoted in lines:
            continue
        try:
            all_start = lines.index("__all__ = [")
        except ValueError:
            raise SystemExit("couldn't find `__all__ = [` in __init__.py")
        for i in range(all_start + 1, len(lines)):
            line = lines[i]
            if line == "]":
                lines.insert(i, quoted)
                break
            m = re.match(r'    "(.+)",', line)
            if m and m.group(1) > entry:
                lines.insert(i, quoted)
                break

    INIT_PY.write_text("\n".join(lines) + "\n")


# ---------------------------------------------------------------------------
# 4. core/client_wrapper.py — banner comment.
# ---------------------------------------------------------------------------

WRAPPER_BANNER = (
    "# This file was auto-generated by Fern from our API Definition.\n"
    "# Hand-edited: auth is handled by the `RiverMarketsSigner` httpx.Auth\n"
    "# attached to the underlying httpx client. Confirm no `x-api-key` header\n"
    "# sneaks back in here after `fern generate`.\n"
)


def patch_wrapper_py() -> None:
    text = WRAPPER_PY.read_text()
    if "RiverMarketsSigner" in text:
        return
    text = text.replace(
        "# This file was auto-generated by Fern from our API Definition.\n",
        WRAPPER_BANNER,
        1,
    )
    WRAPPER_PY.write_text(text)


# ---------------------------------------------------------------------------
# 5. Cleanup.
# ---------------------------------------------------------------------------


def remove_tests_dir() -> None:
    if TESTS_DIR.exists():
        shutil.rmtree(TESTS_DIR)


# ---------------------------------------------------------------------------
# Entry point.
# ---------------------------------------------------------------------------


def main() -> None:
    restore_templates()
    patch_client_py()
    patch_init_py()
    patch_wrapper_py()
    remove_tests_dir()
    print("postprocess: hand-edits re-applied")


if __name__ == "__main__":
    main()
