# This file was auto-generated by Fern from our API Definition.

import typing
from ..core.client_wrapper import SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.order_list_response import OrderListResponse
from ..core.pydantic_utilities import parse_obj_as
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.http_validation_error import HttpValidationError
from json.decoder import JSONDecodeError
from ..core.api_error import ApiError
from .types.order_create_order_type import OrderCreateOrderType
from .types.order_create_time_in_force import OrderCreateTimeInForce
import datetime as dt
from ..types.conditional_order_create import ConditionalOrderCreate
from ..types.order_create_response import OrderCreateResponse
from ..core.serialization import convert_and_respect_annotation_metadata
from ..types.order_detail_response import OrderDetailResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..types.cancel_order_response import CancelOrderResponse
from ..types.order_edit_response import OrderEditResponse
from ..core.client_wrapper import AsyncClientWrapper

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class OrdersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_orders(
        self,
        *,
        status: typing.Optional[str] = None,
        river_id: typing.Optional[int] = None,
        generic_asset_id: typing.Optional[str] = None,
        subaccount_id: typing.Optional[str] = None,
        parent_iceberg_order_id: typing.Optional[str] = None,
        parent_peg_order_id: typing.Optional[str] = None,
        parent_smart_taker_order_id: typing.Optional[str] = None,
        buy_flag: typing.Optional[bool] = None,
        search: typing.Optional[str] = None,
        show_tp_sl_active: typing.Optional[bool] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OrderListResponse:
        """
        List orders with optional filters.

        Returns a paginated list of orders across all accessible subaccounts, ordered by `created_at` descending.

        **Filters:**
        All filters are optional and can be combined. If no `subaccount_id` is specified,
        returns orders from all subaccounts the user has access to.

        **Order Statuses:**
        - `PENDING_SUBMISSION`: Order received, awaiting exchange submission.
        - `PROCESSING`: Being processed by the order consumer.
        - `RESTING`: Live on the exchange order book (may include partially-filled live orders).
        - `EXECUTED`: Terminal — fully filled.
        - `PARTIALLY_FILLED`: Terminal — cancelled with some quantity filled.
        - `CANCELLED`: Terminal — cancelled with no fills.
        - `REJECTED`: Rejected by exchange (see order details for reason).

        **Aggregated Fields:**
        Each order includes `traded_qty`, `average_price`, and `fees_paid` computed from fills.

        Parameters
        ----------
        status : typing.Optional[str]
            Filter by order status. Accepts a single OrderStatus name (e.g. 'RESTING') or the meta-value 'ACTIVE' which resolves to RESTING.

        river_id : typing.Optional[int]
            Filter by instrument ID

        generic_asset_id : typing.Optional[str]
            Filter by generic asset ID

        subaccount_id : typing.Optional[str]
            Filter to a specific subaccount

        parent_iceberg_order_id : typing.Optional[str]
            Filter to child tranches of a specific iceberg parent.

        parent_peg_order_id : typing.Optional[str]
            Filter to child tranches of a specific peg parent.

        parent_smart_taker_order_id : typing.Optional[str]
            Filter to IOC children of a specific smart-taker parent.

        buy_flag : typing.Optional[bool]
            Filter by direction: true=buys, false=sells

        search : typing.Optional[str]
            Free-text search across the order's market: ticker/slug, the human-readable question (event title, market name, outcome) via full-text + substring match, plus the order's river_id / order id / generic asset id. Applied server-side over all matching orders, not just the current page.

        show_tp_sl_active : typing.Optional[bool]
            When true, complex_order_ids only includes attached TP/SL orders with status PENDING or ACTIVE.

        limit : typing.Optional[int]
            Results per page (max 1000)

        offset : typing.Optional[int]
            Pagination offset

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrderListResponse
            Successful Response

        Examples
        --------
        from rivermarkets import RiverMarkets

        client = RiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )
        client.orders.list_orders()
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/orders",
            method="GET",
            params={
                "status": status,
                "river_id": river_id,
                "generic_asset_id": generic_asset_id,
                "subaccount_id": subaccount_id,
                "parent_iceberg_order_id": parent_iceberg_order_id,
                "parent_peg_order_id": parent_peg_order_id,
                "parent_smart_taker_order_id": parent_smart_taker_order_id,
                "buy_flag": buy_flag,
                "search": search,
                "show_tp_sl_active": show_tp_sl_active,
                "limit": limit,
                "offset": offset,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    OrderListResponse,
                    parse_obj_as(
                        type_=OrderListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def create_order(
        self,
        *,
        order_type: OrderCreateOrderType,
        time_in_force: OrderCreateTimeInForce,
        qty: float,
        buy_flag: bool,
        subaccount_id: str,
        price: typing.Optional[float] = OMIT,
        post_only: typing.Optional[bool] = OMIT,
        cancel_order_on_pause: typing.Optional[bool] = OMIT,
        river_id: typing.Optional[int] = OMIT,
        generic_asset_id: typing.Optional[str] = OMIT,
        expiry_ts_utc: typing.Optional[dt.datetime] = OMIT,
        conditional_orders_params: typing.Optional[
            typing.Sequence[ConditionalOrderCreate]
        ] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OrderCreateResponse:
        """
        Place a new order.

        Submits an order for asynchronous processing. The order is persisted immediately
        and queued for execution on the target exchange.

        See  [Orders](https://docs.rivermarkets.com/concepts/orders) and [Order Types](https://docs.rivermarkets.com/concepts/order-types) for more information.

        **Asset Selection:**
        Provide exactly one of `river_id` (standard instrument) or `generic_asset_id` (user-defined basket).
        Generic asset orders only support `MARKET` order type — the system automatically routes
        IOC limit orders to each underlying instrument at optimal prices.

        **Response:**
        Returns `202 Accepted` with the order_id and associated complex_orders ids (TP/SL).
        Poll `GET /v1/orders/{order_id}` or use webhooks to track execution.

        Parameters
        ----------
        order_type : OrderCreateOrderType
            Order type: 'LIMIT' or 'MARKET'

        time_in_force : OrderCreateTimeInForce
            Time in force: 'FOK', 'GTC', 'GTD', or 'IOC'

        qty : float
            Order quantity (number of contracts)

        buy_flag : bool
            Order direction: true=buy, false=sell

        subaccount_id : str
            Subaccount to place the order under

        price : typing.Optional[float]
            Limit price between 0 and 1. Required for LIMIT orders.

        post_only : typing.Optional[bool]
            If true, the order is rejected instead of taking liquidity. Only valid for LIMIT orders with a resting time in force (GTC or GTD).

        cancel_order_on_pause : typing.Optional[bool]
            Kalshi only: if true, the resting order is cancelled by the exchange when it enters a trading pause. Ignored on other venues.

        river_id : typing.Optional[int]
            Instrument ID. Mutually exclusive with generic_asset_id.

        generic_asset_id : typing.Optional[str]
            Generic asset basket UUID. Mutually exclusive with river_id.

        expiry_ts_utc : typing.Optional[dt.datetime]
            Expiry timestamp in UTC(ISO 8601). Required for GTD orders. i.e '2023-11-07T05:31:56Z'

        conditional_orders_params : typing.Optional[typing.Sequence[ConditionalOrderCreate]]
            Optional list of conditional orders (TP/SL) to attach to this order.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrderCreateResponse
            Successful Response

        Examples
        --------
        from rivermarkets import RiverMarkets

        client = RiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )
        client.orders.create_order(
            order_type="LIMIT",
            time_in_force="FOK",
            qty=1.1,
            buy_flag=True,
            subaccount_id="subaccount_id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/orders",
            method="POST",
            json={
                "order_type": order_type,
                "time_in_force": time_in_force,
                "qty": qty,
                "price": price,
                "buy_flag": buy_flag,
                "post_only": post_only,
                "cancel_order_on_pause": cancel_order_on_pause,
                "river_id": river_id,
                "generic_asset_id": generic_asset_id,
                "subaccount_id": subaccount_id,
                "expiry_ts_utc": expiry_ts_utc,
                "conditional_orders_params": convert_and_respect_annotation_metadata(
                    object_=conditional_orders_params,
                    annotation=typing.Sequence[ConditionalOrderCreate],
                    direction="write",
                ),
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    OrderCreateResponse,
                    parse_obj_as(
                        type_=OrderCreateResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def get_order(
        self, order_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> OrderDetailResponse:
        """
        Get a single order by ID with its fills.

        Returns complete order details including execution history.

        **Use Cases:**
        - Track order progress and execution quality
        - Reconcile fills for accounting
        - Debug rejected or partially filled orders

        Parameters
        ----------
        order_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrderDetailResponse
            Successful Response

        Examples
        --------
        from rivermarkets import RiverMarkets

        client = RiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )
        client.orders.get_order(
            order_id="order_id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/orders/{jsonable_encoder(order_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    OrderDetailResponse,
                    parse_obj_as(
                        type_=OrderDetailResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def cancel_order(
        self, order_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CancelOrderResponse:
        """
        Cancel an existing order.

        Request cancellation of an order.
        Returns 202 Accepted with order state - cancellation is processed asynchronously.

        Parameters
        ----------
        order_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CancelOrderResponse
            Successful Response

        Examples
        --------
        from rivermarkets import RiverMarkets

        client = RiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )
        client.orders.cancel_order(
            order_id="order_id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/orders/{jsonable_encoder(order_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    CancelOrderResponse,
                    parse_obj_as(
                        type_=CancelOrderResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def edit_order(
        self,
        order_id: str,
        *,
        qty: typing.Optional[float] = OMIT,
        price: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OrderEditResponse:
        """
        Edit (amend) a resting simple limit order.

        Only `qty` and `price` are editable. `qty` is the new TOTAL quantity (not remaining).
        The order must be RESTING, a simple order (no iceberg/peg parent), a single-instrument
        LIMIT order. Returns 202 Accepted; final status is delivered via the orders WS.

        Parameters
        ----------
        order_id : str

        qty : typing.Optional[float]
            New total order quantity

        price : typing.Optional[float]
            New limit price (between 0 and 1)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrderEditResponse
            Successful Response

        Examples
        --------
        from rivermarkets import RiverMarkets

        client = RiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )
        client.orders.edit_order(
            order_id="order_id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/orders/{jsonable_encoder(order_id)}",
            method="PATCH",
            json={
                "qty": qty,
                "price": price,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    OrderEditResponse,
                    parse_obj_as(
                        type_=OrderEditResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def cancel_all_orders(
        self,
        *,
        subaccount_id: str,
        river_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CancelOrderResponse:
        """
        Cancel all open orders for a subaccount.

        If `river_ids` is set, only orders on those instruments are cancelled;
        it must be omitted/null or non-empty. Cancellation is processed
        asynchronously by the order consumer.

        Parameters
        ----------
        subaccount_id : str

        river_ids : typing.Optional[typing.Sequence[int]]
            If set, only cancel open orders for these instruments; otherwise cancel all open orders on the subaccount. Must be either omitted/null or a non-empty list.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CancelOrderResponse
            Successful Response

        Examples
        --------
        from rivermarkets import RiverMarkets

        client = RiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )
        client.orders.cancel_all_orders(
            subaccount_id="subaccount_id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/orders/cancel-all",
            method="POST",
            json={
                "subaccount_id": subaccount_id,
                "river_ids": river_ids,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    CancelOrderResponse,
                    parse_obj_as(
                        type_=CancelOrderResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)


class AsyncOrdersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_orders(
        self,
        *,
        status: typing.Optional[str] = None,
        river_id: typing.Optional[int] = None,
        generic_asset_id: typing.Optional[str] = None,
        subaccount_id: typing.Optional[str] = None,
        parent_iceberg_order_id: typing.Optional[str] = None,
        parent_peg_order_id: typing.Optional[str] = None,
        parent_smart_taker_order_id: typing.Optional[str] = None,
        buy_flag: typing.Optional[bool] = None,
        search: typing.Optional[str] = None,
        show_tp_sl_active: typing.Optional[bool] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OrderListResponse:
        """
        List orders with optional filters.

        Returns a paginated list of orders across all accessible subaccounts, ordered by `created_at` descending.

        **Filters:**
        All filters are optional and can be combined. If no `subaccount_id` is specified,
        returns orders from all subaccounts the user has access to.

        **Order Statuses:**
        - `PENDING_SUBMISSION`: Order received, awaiting exchange submission.
        - `PROCESSING`: Being processed by the order consumer.
        - `RESTING`: Live on the exchange order book (may include partially-filled live orders).
        - `EXECUTED`: Terminal — fully filled.
        - `PARTIALLY_FILLED`: Terminal — cancelled with some quantity filled.
        - `CANCELLED`: Terminal — cancelled with no fills.
        - `REJECTED`: Rejected by exchange (see order details for reason).

        **Aggregated Fields:**
        Each order includes `traded_qty`, `average_price`, and `fees_paid` computed from fills.

        Parameters
        ----------
        status : typing.Optional[str]
            Filter by order status. Accepts a single OrderStatus name (e.g. 'RESTING') or the meta-value 'ACTIVE' which resolves to RESTING.

        river_id : typing.Optional[int]
            Filter by instrument ID

        generic_asset_id : typing.Optional[str]
            Filter by generic asset ID

        subaccount_id : typing.Optional[str]
            Filter to a specific subaccount

        parent_iceberg_order_id : typing.Optional[str]
            Filter to child tranches of a specific iceberg parent.

        parent_peg_order_id : typing.Optional[str]
            Filter to child tranches of a specific peg parent.

        parent_smart_taker_order_id : typing.Optional[str]
            Filter to IOC children of a specific smart-taker parent.

        buy_flag : typing.Optional[bool]
            Filter by direction: true=buys, false=sells

        search : typing.Optional[str]
            Free-text search across the order's market: ticker/slug, the human-readable question (event title, market name, outcome) via full-text + substring match, plus the order's river_id / order id / generic asset id. Applied server-side over all matching orders, not just the current page.

        show_tp_sl_active : typing.Optional[bool]
            When true, complex_order_ids only includes attached TP/SL orders with status PENDING or ACTIVE.

        limit : typing.Optional[int]
            Results per page (max 1000)

        offset : typing.Optional[int]
            Pagination offset

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrderListResponse
            Successful Response

        Examples
        --------
        import asyncio

        from rivermarkets import AsyncRiverMarkets

        client = AsyncRiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.orders.list_orders()


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/orders",
            method="GET",
            params={
                "status": status,
                "river_id": river_id,
                "generic_asset_id": generic_asset_id,
                "subaccount_id": subaccount_id,
                "parent_iceberg_order_id": parent_iceberg_order_id,
                "parent_peg_order_id": parent_peg_order_id,
                "parent_smart_taker_order_id": parent_smart_taker_order_id,
                "buy_flag": buy_flag,
                "search": search,
                "show_tp_sl_active": show_tp_sl_active,
                "limit": limit,
                "offset": offset,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    OrderListResponse,
                    parse_obj_as(
                        type_=OrderListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def create_order(
        self,
        *,
        order_type: OrderCreateOrderType,
        time_in_force: OrderCreateTimeInForce,
        qty: float,
        buy_flag: bool,
        subaccount_id: str,
        price: typing.Optional[float] = OMIT,
        post_only: typing.Optional[bool] = OMIT,
        cancel_order_on_pause: typing.Optional[bool] = OMIT,
        river_id: typing.Optional[int] = OMIT,
        generic_asset_id: typing.Optional[str] = OMIT,
        expiry_ts_utc: typing.Optional[dt.datetime] = OMIT,
        conditional_orders_params: typing.Optional[
            typing.Sequence[ConditionalOrderCreate]
        ] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OrderCreateResponse:
        """
        Place a new order.

        Submits an order for asynchronous processing. The order is persisted immediately
        and queued for execution on the target exchange.

        See  [Orders](https://docs.rivermarkets.com/concepts/orders) and [Order Types](https://docs.rivermarkets.com/concepts/order-types) for more information.

        **Asset Selection:**
        Provide exactly one of `river_id` (standard instrument) or `generic_asset_id` (user-defined basket).
        Generic asset orders only support `MARKET` order type — the system automatically routes
        IOC limit orders to each underlying instrument at optimal prices.

        **Response:**
        Returns `202 Accepted` with the order_id and associated complex_orders ids (TP/SL).
        Poll `GET /v1/orders/{order_id}` or use webhooks to track execution.

        Parameters
        ----------
        order_type : OrderCreateOrderType
            Order type: 'LIMIT' or 'MARKET'

        time_in_force : OrderCreateTimeInForce
            Time in force: 'FOK', 'GTC', 'GTD', or 'IOC'

        qty : float
            Order quantity (number of contracts)

        buy_flag : bool
            Order direction: true=buy, false=sell

        subaccount_id : str
            Subaccount to place the order under

        price : typing.Optional[float]
            Limit price between 0 and 1. Required for LIMIT orders.

        post_only : typing.Optional[bool]
            If true, the order is rejected instead of taking liquidity. Only valid for LIMIT orders with a resting time in force (GTC or GTD).

        cancel_order_on_pause : typing.Optional[bool]
            Kalshi only: if true, the resting order is cancelled by the exchange when it enters a trading pause. Ignored on other venues.

        river_id : typing.Optional[int]
            Instrument ID. Mutually exclusive with generic_asset_id.

        generic_asset_id : typing.Optional[str]
            Generic asset basket UUID. Mutually exclusive with river_id.

        expiry_ts_utc : typing.Optional[dt.datetime]
            Expiry timestamp in UTC(ISO 8601). Required for GTD orders. i.e '2023-11-07T05:31:56Z'

        conditional_orders_params : typing.Optional[typing.Sequence[ConditionalOrderCreate]]
            Optional list of conditional orders (TP/SL) to attach to this order.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrderCreateResponse
            Successful Response

        Examples
        --------
        import asyncio

        from rivermarkets import AsyncRiverMarkets

        client = AsyncRiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.orders.create_order(
                order_type="LIMIT",
                time_in_force="FOK",
                qty=1.1,
                buy_flag=True,
                subaccount_id="subaccount_id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/orders",
            method="POST",
            json={
                "order_type": order_type,
                "time_in_force": time_in_force,
                "qty": qty,
                "price": price,
                "buy_flag": buy_flag,
                "post_only": post_only,
                "cancel_order_on_pause": cancel_order_on_pause,
                "river_id": river_id,
                "generic_asset_id": generic_asset_id,
                "subaccount_id": subaccount_id,
                "expiry_ts_utc": expiry_ts_utc,
                "conditional_orders_params": convert_and_respect_annotation_metadata(
                    object_=conditional_orders_params,
                    annotation=typing.Sequence[ConditionalOrderCreate],
                    direction="write",
                ),
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    OrderCreateResponse,
                    parse_obj_as(
                        type_=OrderCreateResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def get_order(
        self, order_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> OrderDetailResponse:
        """
        Get a single order by ID with its fills.

        Returns complete order details including execution history.

        **Use Cases:**
        - Track order progress and execution quality
        - Reconcile fills for accounting
        - Debug rejected or partially filled orders

        Parameters
        ----------
        order_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrderDetailResponse
            Successful Response

        Examples
        --------
        import asyncio

        from rivermarkets import AsyncRiverMarkets

        client = AsyncRiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.orders.get_order(
                order_id="order_id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/orders/{jsonable_encoder(order_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    OrderDetailResponse,
                    parse_obj_as(
                        type_=OrderDetailResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def cancel_order(
        self, order_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CancelOrderResponse:
        """
        Cancel an existing order.

        Request cancellation of an order.
        Returns 202 Accepted with order state - cancellation is processed asynchronously.

        Parameters
        ----------
        order_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CancelOrderResponse
            Successful Response

        Examples
        --------
        import asyncio

        from rivermarkets import AsyncRiverMarkets

        client = AsyncRiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.orders.cancel_order(
                order_id="order_id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/orders/{jsonable_encoder(order_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    CancelOrderResponse,
                    parse_obj_as(
                        type_=CancelOrderResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def edit_order(
        self,
        order_id: str,
        *,
        qty: typing.Optional[float] = OMIT,
        price: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OrderEditResponse:
        """
        Edit (amend) a resting simple limit order.

        Only `qty` and `price` are editable. `qty` is the new TOTAL quantity (not remaining).
        The order must be RESTING, a simple order (no iceberg/peg parent), a single-instrument
        LIMIT order. Returns 202 Accepted; final status is delivered via the orders WS.

        Parameters
        ----------
        order_id : str

        qty : typing.Optional[float]
            New total order quantity

        price : typing.Optional[float]
            New limit price (between 0 and 1)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrderEditResponse
            Successful Response

        Examples
        --------
        import asyncio

        from rivermarkets import AsyncRiverMarkets

        client = AsyncRiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.orders.edit_order(
                order_id="order_id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/orders/{jsonable_encoder(order_id)}",
            method="PATCH",
            json={
                "qty": qty,
                "price": price,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    OrderEditResponse,
                    parse_obj_as(
                        type_=OrderEditResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def cancel_all_orders(
        self,
        *,
        subaccount_id: str,
        river_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CancelOrderResponse:
        """
        Cancel all open orders for a subaccount.

        If `river_ids` is set, only orders on those instruments are cancelled;
        it must be omitted/null or non-empty. Cancellation is processed
        asynchronously by the order consumer.

        Parameters
        ----------
        subaccount_id : str

        river_ids : typing.Optional[typing.Sequence[int]]
            If set, only cancel open orders for these instruments; otherwise cancel all open orders on the subaccount. Must be either omitted/null or a non-empty list.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CancelOrderResponse
            Successful Response

        Examples
        --------
        import asyncio

        from rivermarkets import AsyncRiverMarkets

        client = AsyncRiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.orders.cancel_all_orders(
                subaccount_id="subaccount_id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/orders/cancel-all",
            method="POST",
            json={
                "subaccount_id": subaccount_id,
                "river_ids": river_ids,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    CancelOrderResponse,
                    parse_obj_as(
                        type_=CancelOrderResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)
