# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import datetime as dt
import typing


class ApiKeyRotateResponse(UniversalBaseModel):
    """
    Response when rotating an API key.

    The old key is revoked and a new key is generated.
    IMPORTANT: The `key` field is only shown once.
    """

    id: str
    key: str = pydantic.Field()
    """
    New API key - shown only once, save it now!
    """

    name: str
    created_at: dt.datetime

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
