# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import datetime as dt
import typing


class ApiKeyCreateResponse(UniversalBaseModel):
    """
    Response when creating an API key.

    IMPORTANT: The `key` field contains the full API key and is only
    returned ONCE at creation time. It cannot be retrieved again.
    The user must save it immediately.
    """

    id: str
    key: str = pydantic.Field()
    """
    Full API key - shown only once, save it now!
    """

    name: str
    created_at: dt.datetime

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
