# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing
import datetime as dt


class ApiKeyResponse(UniversalBaseModel):
    """
    Schema for API key metadata (does not include the actual key).

    Used for listing keys - the actual key is never shown after creation.
    """

    id: str
    name: str
    prefix: str = pydantic.Field()
    """
    Key prefix for identification
    """

    scope: typing.Optional[str] = None
    created_at: dt.datetime
    last_used_at: typing.Optional[dt.datetime] = None
    expires_at: dt.datetime
    is_revoked: bool

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
