# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing


class BuildParlayResponse(UniversalBaseModel):
    """
    The tradable combo market for the legs: pass market_ticker to POST /v1/rfqs.
    """

    market_ticker: str = pydantic.Field()
    """
    Kalshi parlay ticker or Polymarket US combo symbol
    """

    river_id: typing.Optional[int] = pydantic.Field(default=None)
    """
    River id of the combo, Polymarket US only
    """

    event_ticker: typing.Optional[str] = pydantic.Field(default=None)
    """
    Kalshi only
    """

    collection_ticker: typing.Optional[str] = pydantic.Field(default=None)
    """
    Kalshi only: the collection used
    """

    collection_title: typing.Optional[str] = pydantic.Field(default=None)
    """
    Kalshi only
    """

    candidate_collections: typing.Optional[typing.List[str]] = pydantic.Field(
        default=None
    )
    """
    Kalshi only
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
