# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing
from .conditional_order_response import ConditionalOrderResponse
from .iceberg_order_response import IcebergOrderResponse
from .peg_order_response import PegOrderResponse
from .smart_taker_order_response import SmartTakerOrderResponse


class ComplexOrderResponse(UniversalBaseModel):
    """
    Schema for a complex order response (unified across all complex order types).
    """

    complex_order_id: str = pydantic.Field()
    """
    Unique complex order identifier
    """

    complex_order_type: str = pydantic.Field()
    """
    Complex order type: CONDITIONAL, TWAP, etc.
    """

    complex_order_subtype: typing.Optional[str] = pydantic.Field(default=None)
    """
    Complex order subtype: TP, SL, STOP, etc.
    """

    subaccount_id: str = pydantic.Field()
    """
    Subaccount the order belongs to
    """

    river_id: typing.Optional[int] = pydantic.Field(default=None)
    """
    Instrument ID
    """

    generic_asset_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Generic asset basket ID
    """

    status: str = pydantic.Field()
    """
    Order status (interpretation depends on complex_order_type)
    """

    created_at: str = pydantic.Field()
    """
    Creation timestamp (UTC)
    """

    updated_at: str = pydantic.Field()
    """
    Last update timestamp (UTC)
    """

    conditional_order: typing.Optional[ConditionalOrderResponse] = pydantic.Field(
        default=None
    )
    """
    Conditional order detail
    """

    iceberg_order: typing.Optional[IcebergOrderResponse] = pydantic.Field(default=None)
    """
    Iceberg order detail
    """

    peg_order: typing.Optional[PegOrderResponse] = pydantic.Field(default=None)
    """
    Peg order detail
    """

    smart_taker_order: typing.Optional[SmartTakerOrderResponse] = pydantic.Field(
        default=None
    )
    """
    Smart-taker order detail
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
