# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing


class ComplexOrderCreateResponse(UniversalBaseModel):
    """
    Schema for a complex order response (unified across all complex order types).
    """

    complex_order_id: str = pydantic.Field()
    """
    Unique complex order identifier
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
