# This file was auto-generated by Fern from our API Definition.

import typing

ConditionalOrderCreateConditionalOrderType = typing.Union[
    typing.Literal["TP", "SL", "STOP", "REVERSE_STOP"], typing.Any
]
