# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic


class ConditionalOrderResponse(UniversalBaseModel):
    parent_river_order_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Parent order ID
    """

    parent_complex_order_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Parent complex order ID
    """

    conditional_order_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    TP, SL, or STOP
    """

    stop_order_price: typing.Optional[float] = pydantic.Field(default=None)
    """
    Trigger price
    """

    trigger_stop_order_price: typing.Optional[float] = pydantic.Field(default=None)
    """
    Trigger price for stop triggered orders
    """

    trigger_order_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    LIMIT or MARKET
    """

    trigger_order_qty: typing.Optional[float] = pydantic.Field(default=None)
    """
    Trigger quantity
    """

    trigger_order_limit_price: typing.Optional[float] = pydantic.Field(default=None)
    """
    Trigger limit price
    """

    trigger_order_buy_flag: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Trigger direction
    """

    trigger_river_order_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Triggered order ID
    """

    trigger_complex_order_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Triggered complex order ID
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
