# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
from .conditional_order_create_conditional_order_type import (
    ConditionalOrderCreateConditionalOrderType,
)
import pydantic
import typing
from .trigger_order import TriggerOrder


class ConditionalOrderCreate(UniversalBaseModel):
    """
    Schema for a conditional order (take profit or stop loss) attached to a parent order.
    """

    conditional_order_type: ConditionalOrderCreateConditionalOrderType = (
        pydantic.Field()
    )
    """
    Type of conditional order: TP (take profit), SL (stop loss), or STOP
    """

    stop_order_price: typing.Optional[float] = pydantic.Field(default=None)
    """
    Activation price for STOP conditional orders. This is the price at which the conditional order triggers and places the trigger_order.
    """

    trigger_order: TriggerOrder = pydantic.Field()
    """
    The order that gets placed when the conditional order activates. For TP/SL this happens after the parent order fills; for STOP this happens when stop_order_price is reached.
    """

    parent_river_order_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Parent order ID (required for TP and SL)
    """

    parent_complex_order_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Parent complex order ID (for chaining)
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
