# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing


class CreateRfqResponse(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    The exchange's RFQ id; the handle for quotes, accept and cancel
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
