# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .market_search_result import MarketSearchResult
import datetime as dt
import pydantic


class CustomAssetDetailResponse(UniversalBaseModel):
    """
    Response schema for a custom asset with its members (detail view).
    """

    custom_asset_id: str
    subaccount_id: str
    name: str
    description: typing.Optional[str] = None
    members: typing.List[MarketSearchResult]
    inserted_at: dt.datetime = pydantic.Field()
    """
    Creation timestamp (UTC)
    """

    updated_at: dt.datetime = pydantic.Field()
    """
    Last update timestamp (UTC)
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
