# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import datetime as dt
import pydantic


class CustomAssetResponse(UniversalBaseModel):
    """
    Response schema for a custom asset (list view).
    """

    custom_asset_id: str
    subaccount_id: str
    name: str
    description: typing.Optional[str] = None
    inserted_at: dt.datetime
    updated_at: dt.datetime

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
