# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .exchange_balance import ExchangeBalance
import pydantic


class ExchangeBalanceResponse(UniversalBaseModel):
    subaccount_id: str
    balances: typing.List[ExchangeBalance]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
