# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing


class FairValueItem(UniversalBaseModel):
    """
    One (instrument, fair value) pair within a batch upsert.
    """

    river_id: int
    fair_value: float = pydantic.Field()
    """
    Probability in [0, 1]
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
