# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .fair_value_response import FairValueResponse
import pydantic


class FairValueListResponse(UniversalBaseModel):
    fair_values: typing.List[FairValueResponse]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
