# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic

from ..core.pydantic_utilities import UniversalBaseModel
from .fee_schedule_response import FeeScheduleResponse


class FeeScheduleLookupResponse(UniversalBaseModel):
    schedules: typing.List[FeeScheduleResponse]
    missing_river_ids: typing.List[int]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
