# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic

from ..core.pydantic_utilities import UniversalBaseModel
from .fee_rounding import FeeRounding


class FeeRuleResponse(UniversalBaseModel):
    coefficient: str
    rounding: FeeRounding
    pre_ceiling_cent_decimals: typing.Optional[int]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
