# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
from .fee_rounding import FeeRounding
import typing


class FeeRuleResponse(UniversalBaseModel):
    coefficient: str = pydantic.Field()
    """
    Decimal multiplier in fee = quantity × coefficient × price × (1 - price).
    """

    rounding: FeeRounding
    pre_ceiling_cent_decimals: typing.Optional[int] = pydantic.Field(default=None)
    """
    Decimal places used to stabilize fee × 100 before applying ceil_cent.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
