# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
from .fee_model import FeeModel
from .fee_rule_response import FeeRuleResponse
import pydantic
import typing


class FeeScheduleResponse(UniversalBaseModel):
    river_id: int
    exchange: str
    model: FeeModel
    maker: FeeRuleResponse
    taker: FeeRuleResponse
    schedule_version: str = pydantic.Field()
    """
    Stable fingerprint of the normalized schedule.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
