# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic


class FillResponse(UniversalBaseModel):
    """
    Schema for fill response.
    """

    river_id: int
    client_order_id: typing.Optional[str] = None
    exchange_order_id: str
    exchange_trade_id: str
    exchange_timestamp: str = pydantic.Field()
    """
    Execution timestamp from exchange (UTC)
    """

    price: float
    qty: float
    fee: float
    buy_flag: bool
    is_maker: bool
    counterparty_address: typing.Optional[str] = None
    counterparty_exchange_order_id: typing.Optional[str] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
