# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
from .generic_entity import GenericEntity
import typing
import pydantic


class GenericEventParticipant(UniversalBaseModel):
    entity: GenericEntity
    role: typing.Optional[str] = pydantic.Field(default=None)
    """
    'home' | 'away' for two-sided games, NULL otherwise
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
