# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import datetime as dt
from .market_search_result import MarketSearchResult
import pydantic


class GenericAssetDetailResponse(UniversalBaseModel):
    """
    Response schema for a generic asset with its resolved members (detail view).
    """

    generic_asset_id: str
    owner_subaccount_id: typing.Optional[str] = None
    name: str
    description: typing.Optional[str] = None
    category: typing.Optional[str] = None
    subcategory: typing.Optional[str] = None
    resolves_at: typing.Optional[dt.datetime] = None
    status: typing.Optional[str] = None
    members: typing.List[MarketSearchResult]
    inserted_at: str = pydantic.Field()
    """
    Creation timestamp (UTC)
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
