# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from .generic_event_participant import GenericEventParticipant


class GenericEventResponse(UniversalBaseModel):
    """
    The generic event (normalization.events) an auto-matched asset settles on.
    """

    event_id: str
    series: typing.Optional[str] = pydantic.Field(default=None)
    """
    League / series name, e.g. NFL
    """

    start: typing.Optional[str] = pydantic.Field(default=None)
    """
    Event start (UTC)
    """

    title: typing.Optional[str] = pydantic.Field(default=None)
    """
    'AWAY @ HOME' for games, with (G2) for doubleheaders; 'A vs B' where there is no home side
    """

    participants: typing.Optional[typing.List[GenericEventParticipant]] = (
        pydantic.Field(default=None)
    )
    """
    Away first then home for games; name order otherwise
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
