# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing


class GenericEntity(UniversalBaseModel):
    """
    Whatever an asset or event is about: a team, or a player in an individual sport.
    """

    entity_id: str
    name: str = pydantic.Field()
    """
    Display name, e.g. 'Seattle Seahawks' or 'Carlos Alcaraz'
    """

    abbreviation: typing.Optional[str] = pydantic.Field(default=None)
    """
    Short code for a team ('SEA'), last name for a person ('Alcaraz')
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
