# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
import datetime as dt


class IcebergOrderResponse(UniversalBaseModel):
    """
    Iceberg-specific runtime detail returned alongside a ComplexOrderResponse.

    Sourced from `view_iceberg_orders` so it includes derived fields
    (executed_qty, remaining_qty).
    """

    buy_flag: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Direction
    """

    total_qty: typing.Optional[float] = pydantic.Field(default=None)
    """
    Total iceberg quantity
    """

    displayed_qty: typing.Optional[float] = pydantic.Field(default=None)
    """
    Tranche size
    """

    limit_price: typing.Optional[float] = pydantic.Field(default=None)
    """
    Static limit price for every tranche
    """

    post_only: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether tranches are posted as post-only
    """

    reload_delay_s: typing.Optional[int] = pydantic.Field(default=None)
    """
    Inter-tranche reload delay in seconds, if set. NULL or 0 = place next tranche immediately.
    """

    executed_qty: typing.Optional[float] = pydantic.Field(default=None)
    """
    Sum of fully-executed child tranches' qty
    """

    remaining_qty: typing.Optional[float] = pydantic.Field(default=None)
    """
    total_qty - executed_qty
    """

    expiry_ts_utc: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Expiry timestamp in UTC, if set. Tranches are submitted as GTD with this expiry.
    """

    reject_reason: typing.Optional[str] = pydantic.Field(default=None)
    """
    Reason for rejection, if any
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
