# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic


class InviteRedeemResponse(UniversalBaseModel):
    """
    Response after attempting to redeem an invite code.
    """

    success: bool
    message: str

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
