# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing


class MakerQuoteResponse(UniversalBaseModel):
    """
    One of our live maker quotes. Same shape as the `quote` frame on
    /v1/ws/rfqs, so a client can hydrate from here after a reconnect and then
    keep following the socket.
    """

    river_order_id: str = pydantic.Field()
    """
    Order id that owns the quote; the handle for confirm and cancel
    """

    river_rfq_id: str = pydantic.Field()
    """
    RFQ this quote answers
    """

    river_id: int = pydantic.Field()
    """
    Instrument (combo market) quoted
    """

    exchange: str
    status: str = pydantic.Field()
    """
    pending | open | accepted | confirmed
    """

    bid: float = pydantic.Field()
    """
    YES-space price to buy YES
    """

    ask: float = pydantic.Field()
    """
    YES-space price to sell YES
    """

    qty: float
    accepted_side: typing.Optional[str] = pydantic.Field(default=None)
    """
    Side of our quote the taker hit, once accepted
    """

    confirm_deadline_ts: typing.Optional[str] = pydantic.Field(default=None)
    """
    Confirm by this time (UTC) or the exchange cancels the quote
    """

    auto_confirm: bool
    created_at: str

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
