# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .market_search_result import MarketSearchResult
import pydantic


class MarketLookupResponse(UniversalBaseModel):
    """
    Schema for market lookup response.
    """

    results: typing.List[MarketSearchResult]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
