# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .market_search_result import MarketSearchResult
import pydantic


class MarketMatchBatchResponse(UniversalBaseModel):
    """
    Batch exact-match response.

    ``results`` holds a full market row (with ``river_id``, ``ticker``, ``slug`` and
    ``exchange_name``) for every identifier that matched. Identifiers with no match are
    echoed back in ``unmatched_tickers`` / ``unmatched_slugs`` so callers can tell the
    difference between "not found" and a lookup they forgot to send.
    """

    results: typing.List[MarketSearchResult]
    unmatched_tickers: typing.Optional[typing.List[str]] = None
    unmatched_slugs: typing.Optional[typing.List[str]] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
