# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing


class OrderEditResponse(UniversalBaseModel):
    """
    Schema for order edit response.
    """

    river_order_id: str = pydantic.Field()
    """
    Unique order identifier
    """

    status: str = pydantic.Field()
    """
    Always PENDING_AMEND. Final status (RESTING on success, REJECTED on failure) is delivered via the orders WS.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
