# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing


class OrderCreateResponse(UniversalBaseModel):
    """
    Schema for order create response.
    """

    river_order_id: str = pydantic.Field()
    """
    Unique order identifier
    """

    complex_orders: typing.Dict[str, typing.List[str]] = pydantic.Field()
    """
    List of complex river orders id
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
