# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .order_response import OrderResponse
import pydantic


class OrderListResponse(UniversalBaseModel):
    """
    Schema for list of orders.
    """

    orders: typing.List[OrderResponse] = pydantic.Field()
    """
    List of orders matching the query
    """

    has_more: bool = pydantic.Field()
    """
    True when more orders exist past this page
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
