# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .order_batch_item_result import OrderBatchItemResult
import pydantic


class OrderBatchCreateResponse(UniversalBaseModel):
    """
    Schema for batch order create response.
    """

    results: typing.List[OrderBatchItemResult] = pydantic.Field()
    """
    One result per requested order, in request order
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
