# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import datetime as dt
import typing


class OrderFillResponse(UniversalBaseModel):
    """
    Schema for a single fill on an order.
    """

    river_id: int = pydantic.Field()
    """
    Instrument ID
    """

    exchange_order_id: str = pydantic.Field()
    """
    Exchange-assigned order ID
    """

    exchange_trade_id: str = pydantic.Field()
    """
    Exchange-assigned trade/fill ID
    """

    exchange_timestamp: dt.datetime = pydantic.Field()
    """
    Execution timestamp from exchange (UTC)
    """

    price: float = pydantic.Field()
    """
    Execution price
    """

    qty: float = pydantic.Field()
    """
    Filled quantity
    """

    fee: float = pydantic.Field()
    """
    Fee charged by the exchange for this fill
    """

    buy_flag: bool = pydantic.Field()
    """
    Fill direction: true=buy, false=sell
    """

    is_maker: bool = pydantic.Field()
    """
    Whether this fill provided liquidity (maker) or took it (taker)
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
