# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing
import datetime as dt


class OrderResponse(UniversalBaseModel):
    """
    Schema for order response, when user request information about an order.
    """

    river_order_id: str = pydantic.Field()
    """
    Unique order identifier
    """

    order_type: str = pydantic.Field()
    """
    Order type: LIMIT or MARKET
    """

    time_in_force: str = pydantic.Field()
    """
    Time in force: FOK, GTC, GTD, or IOC
    """

    qty: float = pydantic.Field()
    """
    Original order quantity
    """

    price: typing.Optional[float] = pydantic.Field(default=None)
    """
    Limit price (null for market orders)
    """

    buy_flag: bool = pydantic.Field()
    """
    Order direction: true=buy, false=sell
    """

    status: str = pydantic.Field()
    """
    Order status: PENDING_SUBMISSION, PROCESSING, RESTING, PARTIALLY_FILLED, EXECUTED, CANCELLED, REJECTED, or EXPIRED
    """

    river_id: typing.Optional[int] = pydantic.Field(default=None)
    """
    Instrument ID
    """

    custom_asset_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Custom asset basket ID
    """

    subaccount_id: str = pydantic.Field()
    """
    Subaccount the order belongs to
    """

    expiry_ts_utc: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Expiry timestamp for GTD orders
    """

    created_at: dt.datetime = pydantic.Field()
    """
    Order creation timestamp (UTC)
    """

    updated_at: dt.datetime = pydantic.Field()
    """
    Last update timestamp (UTC)
    """

    traded_qty: typing.Optional[float] = pydantic.Field(default=None)
    """
    Total quantity filled
    """

    average_price: typing.Optional[float] = pydantic.Field(default=None)
    """
    Volume-weighted average fill price
    """

    fees_paid: typing.Optional[float] = pydantic.Field(default=None)
    """
    Total fees paid across all fills
    """

    complex_order_ids: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    List of complex order identifiers
    """

    reject_reason: typing.Optional[str] = pydantic.Field(default=None)
    """
    Reason for rejection (if status is REJECTED)
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
