# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
from .order_create_order_type import OrderCreateOrderType
import pydantic
from .order_create_time_in_force import OrderCreateTimeInForce
import typing
import datetime as dt
from .conditional_order_create import ConditionalOrderCreate


class OrderCreate(UniversalBaseModel):
    """
    Schema for creating a new order.
    """

    order_type: OrderCreateOrderType = pydantic.Field()
    """
    Order type: 'LIMIT' or 'MARKET'
    """

    time_in_force: OrderCreateTimeInForce = pydantic.Field()
    """
    Time in force: 'FOK', 'GTC', 'GTD', or 'IOC'
    """

    qty: float = pydantic.Field()
    """
    Order quantity (number of contracts)
    """

    price: typing.Optional[float] = pydantic.Field(default=None)
    """
    Limit price between 0 and 1. Required for LIMIT orders.
    """

    buy_flag: bool = pydantic.Field()
    """
    Order direction: true=buy, false=sell
    """

    post_only: typing.Optional[bool] = pydantic.Field(default=None)
    """
    If true, the order is rejected instead of taking liquidity. Only valid for LIMIT orders with a resting time in force (GTC or GTD).
    """

    cancel_order_on_pause: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Kalshi only: if true, the resting order is cancelled by the exchange when it enters a trading pause. Ignored on other venues.
    """

    river_id: typing.Optional[int] = pydantic.Field(default=None)
    """
    Instrument ID. Mutually exclusive with generic_asset_id.
    """

    generic_asset_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Generic asset basket UUID. Mutually exclusive with river_id.
    """

    subaccount_id: str = pydantic.Field()
    """
    Subaccount to place the order under
    """

    expiry_ts_utc: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Expiry timestamp in UTC(ISO 8601). Required for GTD orders. i.e '2023-11-07T05:31:56Z'
    """

    conditional_orders_params: typing.Optional[typing.List[ConditionalOrderCreate]] = (
        pydantic.Field(default=None)
    )
    """
    Optional list of conditional orders (TP/SL) to attach to this order.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
