# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing


class OrderBatchItemError(UniversalBaseModel):
    """
    Rejection detail for one item of a batch.
    """

    code: str = pydantic.Field()
    """
    Machine-readable error code
    """

    message: str = pydantic.Field()
    """
    Human-readable rejection reason
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
