# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing


class PegLegResponse(UniversalBaseModel):
    """
    One member venue of a generic-asset peg: an ordinary peg row on that market.
    """

    peg_order_id: str = pydantic.Field()
    """
    The leg's own peg id
    """

    river_id: int
    exchange_name: typing.Optional[str] = None
    flipped: bool = pydantic.Field()
    """
    Member YES is the opposite of the asset's outcome; leg side and band are inverted
    """

    total_qty: float = pydantic.Field()
    """
    Quantity currently allocated to this leg
    """

    executed_qty: float = pydantic.Field()
    """
    Filled on this leg
    """

    status: str = pydantic.Field()
    """
    Leg peg status
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
