# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic


class PositionResponse(UniversalBaseModel):
    """
    Schema for position response.
    """

    river_id: int
    position: float
    exchange: str
    exchange_name: str

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
