# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .position_response import PositionResponse
import pydantic


class PositionListResponse(UniversalBaseModel):
    """
    Schema for list of positions.
    """

    positions: typing.List[PositionResponse]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
