# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
from .price_response_type import PriceResponseType
import typing
from .price_candlestick import PriceCandlestick
from .price_point import PricePoint
import pydantic


class PriceResponse(UniversalBaseModel):
    """
    Response for price queries.
    """

    river_id: int
    exchange: str
    type: PriceResponseType
    candlesticks: typing.Optional[typing.List[PriceCandlestick]] = None
    history: typing.Optional[typing.List[PricePoint]] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
