# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic


class PriceCandlestick(UniversalBaseModel):
    """
    Candlestick format for all exchanges.
    """

    timestamp: int
    open: float
    high: float
    low: float
    close: float
    volume: typing.Optional[int] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
