# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing


class QuoteResponse(UniversalBaseModel):
    """
    A maker's quote on your RFQ, in YES space on both exchanges: yes_bid_dollars is the
    maker's bid to buy YES (you sell at it), no_bid_dollars the maker's bid to buy NO (you buy
    YES at 1 - no_bid_dollars).
    """

    exchange_quote_id: str = pydantic.Field()
    """
    The exchange's quote id; the handle for accept
    """

    exchange_rfq_id: str
    exchange: typing.Optional[str] = pydantic.Field(default=None)
    """
    kalshi or polymarket_us
    """

    market_ticker: str
    status: str = pydantic.Field()
    """
    open, accepted, confirmed, executed or cancelled
    """

    yes_bid_dollars: typing.Optional[float] = None
    no_bid_dollars: typing.Optional[float] = None
    yes_contracts_fp: typing.Optional[float] = pydantic.Field(default=None)
    """
    Size available at the yes bid
    """

    no_contracts_fp: typing.Optional[float] = pydantic.Field(default=None)
    """
    Size available at the no bid
    """

    contracts_fp: typing.Optional[float] = None
    accepted_buy_flag: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Once accepted: True if you bought YES on this quote, False if you sold
    """

    accepted_ts: typing.Optional[str] = None
    confirmed_ts: typing.Optional[str] = None
    executed_ts: typing.Optional[str] = None
    cancelled_ts: typing.Optional[str] = None
    created_ts: typing.Optional[str] = None
    updated_ts: typing.Optional[str] = None
    rest_remainder: typing.Optional[bool] = None
    post_only: typing.Optional[bool] = None
    cancellation_reason: typing.Optional[str] = None
    creator_id: typing.Optional[str] = None
    creator_user_id: typing.Optional[str] = None
    rfq_creator_user_id: typing.Optional[str] = None
    rfq_creator_order_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Your paired order id once executed
    """

    creator_order_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The maker's paired order id once executed
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
