# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .quote_response import QuoteResponse
import pydantic


class QuoteListResponse(UniversalBaseModel):
    quotes: typing.List[QuoteResponse]
    cursor: typing.Optional[str] = pydantic.Field(default=None)
    """
    Kalshi pagination cursor; absent on Polymarket US
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
