# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .resolve_combos_result import ResolveCombosResult
import pydantic


class ResolveCombosResponse(UniversalBaseModel):
    """
    ``legs`` is empty for river_ids that are not combos or whose legs are not ingested yet.
    """

    results: typing.List[ResolveCombosResult]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
