# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing


class RfqMveLeg(UniversalBaseModel):
    """
    One leg of a Kalshi parlay RFQ.
    """

    event_ticker: str
    market_ticker: str
    side: str = pydantic.Field()
    """
    yes or no
    """

    yes_settlement_value_dollars: typing.Optional[float] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
