# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing


class RfqComboLeg(UniversalBaseModel):
    """
    One leg of a Polymarket US combo RFQ.
    """

    symbol: str = pydantic.Field()
    """
    The leg's market slug
    """

    side: str = pydantic.Field()
    """
    SIDE_BUY: the combo pays when the leg resolves YES; SIDE_SELL: when it resolves NO
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
