# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing


class RfqLeg(UniversalBaseModel):
    """
    A leg in River's vocabulary, the same shape the RFQ stream and POST /v1/parlays/build use.
    """

    river_id: int
    buy_flag: bool = pydantic.Field()
    """
    True: the combo pays when this market resolves YES; False: when it resolves NO
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
