# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing
import datetime as dt


class SmartTakerOrderParams(UniversalBaseModel):
    """
    Parameters for creating a smart-taker complex order.

    A smart-taker rests nothing on the book. It watches the opposite side and
    fires an IOC sweep (at `limit_price`, for the full remaining qty) whenever at
    least `min_qty` of acceptable liquidity (price within `limit_price`) is
    resting on the book — amortising taker fee/spread and refusing to cross into
    a thin book.
    """

    buy_flag: bool = pydantic.Field()
    """
    Direction: true=buy, false=sell
    """

    total_qty: float = pydantic.Field()
    """
    Total quantity to acquire/offload across all IOC clips
    """

    limit_price: float = pydantic.Field()
    """
    Worst price the taker will accept — max for buy, min for sell (between 0 and 1)
    """

    min_qty: float = pydantic.Field()
    """
    Book-depth trigger gate: only fire when at least this much acceptable liquidity sits within limit_price on the opposite side. A depth floor, not a per-clip fill floor — it may exceed total_qty (e.g. 'take my 100 only when >=500 is resting') and an IOC may fill less if liquidity vanishes mid-flight.
    """

    expiry_ts_utc: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Optional expiry timestamp in UTC (ISO 8601). Once it passes, the order stops firing and is torn down by the periodic reconciliation sweep.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
