# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import datetime as dt
import pydantic


class SubaccountResponse(UniversalBaseModel):
    """
    Schema for subaccount response.
    """

    subaccount_id: str
    name: str
    description: typing.Optional[str] = None
    is_active: bool
    inserted_at: dt.datetime

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
