# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .suggestion_group_response import SuggestionGroupResponse
import pydantic


class SuggestionListResponse(UniversalBaseModel):
    """
    Schema for the list of suggestion groups.
    """

    groups: typing.List[SuggestionGroupResponse]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
