# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .suggestion_asset_response import SuggestionAssetResponse
import pydantic


class SuggestionGroupResponse(UniversalBaseModel):
    """
    Schema for a suggestion group with its assets.
    """

    id: int
    tag: str
    name: str
    description: typing.Optional[str] = None
    category: typing.Optional[str] = None
    assets: typing.List[SuggestionAssetResponse]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
