# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import datetime as dt
import pydantic


class TradeprintEvent(UniversalBaseModel):
    """
    A single trade print.

    `aggressor_buy_flag` is true when the aggressing (taker) side bought —
    i.e. the trade hit an ask. The frontend renders side color and "Buy/Sell"
    from this flag.
    """

    exchange_timestamp: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Exchange-reported trade timestamp (UTC)
    """

    price: float
    qty: float
    aggressor_buy_flag: typing.Optional[bool] = None
    exchange_trade_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Exchange-assigned trade id. Used by clients to dedup overlap between REST backfill and WS live stream.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
