# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
from .tradeprints_status import TradeprintsStatus
import typing
from .tradeprint_event import TradeprintEvent
import pydantic


class TradeprintsResponse(UniversalBaseModel):
    """
    Per-market block of recent trades from the exchange.
    """

    status: TradeprintsStatus
    river_id: typing.Optional[int] = None
    trades: typing.Optional[typing.List[TradeprintEvent]] = None
    message: typing.Optional[str] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
