# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .user_fill_list_response_subaccount_to_fills_item_value import (
    UserFillListResponseSubaccountToFillsItemValue,
)
import pydantic


class UserFillListResponse(UniversalBaseModel):
    """
    Schema for list of fills for a user.
    """

    subaccount_to_fills: typing.List[
        typing.Dict[str, UserFillListResponseSubaccountToFillsItemValue]
    ]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
