# This file was auto-generated by Fern from our API Definition.

import typing
from .position_response import PositionResponse

UserPositionListResponseSubaccountToPositionsItemValue = typing.Union[
    str, typing.List[PositionResponse]
]
