# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .validation_error_loc_item import ValidationErrorLocItem
import pydantic


class ValidationError(UniversalBaseModel):
    loc: typing.List[ValidationErrorLocItem]
    msg: str
    type: str

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
