# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic


class WatchlistResponse(UniversalBaseModel):
    """
    A watchlist summary (list view): metadata + ordered member river_ids.
    """

    watchlist_id: str
    name: str
    description: typing.Optional[str] = None
    owner_subaccount_id: str
    river_ids: typing.List[int]
    created_at: str

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
