# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .watchlist_response import WatchlistResponse
import pydantic


class WatchlistListResponse(UniversalBaseModel):
    watchlists: typing.List[WatchlistResponse]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
