# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic


class WatchlistMemberAdd(UniversalBaseModel):
    """
    Request schema for adding members to a watchlist (appended at the end).
    """

    river_ids: typing.List[int]
    flipped: typing.Optional[typing.List[bool]] = pydantic.Field(default=None)
    """
    Parallel to river_ids; True where the member's YES is the opposite of the tracked outcome
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )  # type: ignore # Pydantic v2
