# This file was auto-generated by Fern from our API Definition.

import typing
from ..core.client_wrapper import SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.maker_quote_list_response import MakerQuoteListResponse
from ..core.pydantic_utilities import parse_obj_as
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.http_validation_error import HttpValidationError
from json.decoder import JSONDecodeError
from ..core.api_error import ApiError
from ..types.create_maker_quote_response import CreateMakerQuoteResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.client_wrapper import AsyncClientWrapper

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RfqsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_maker_quotes(
        self,
        *,
        subaccount_id: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MakerQuoteListResponse:
        """
        Live (non-terminal) maker quotes for a subaccount.

        Parameters
        ----------
        subaccount_id : str
            Subaccount whose quotes to list

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MakerQuoteListResponse
            Successful Response

        Examples
        --------
        from rivermarkets import RiverMarkets

        client = RiverMarkets()
        client.rfqs.list_maker_quotes(
            subaccount_id="subaccount_id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/rfqs/quotes",
            method="GET",
            params={
                "subaccount_id": subaccount_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    MakerQuoteListResponse,
                    parse_obj_as(
                        type_=MakerQuoteListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def create_maker_quote(
        self,
        river_rfq_id: str,
        *,
        subaccount_id: str,
        bid: float,
        ask: float,
        auto_confirm: typing.Optional[bool] = OMIT,
        rest_remainder: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateMakerQuoteResponse:
        """
        Quote an RFQ from the /v1/ws/rfqs stream as a maker.

        Parameters
        ----------
        river_rfq_id : str

        subaccount_id : str
            Non-custodial subaccount quoting the RFQ

        bid : float
            YES-space bid: our price to buy YES

        ask : float
            YES-space ask: our price to sell YES (venue no_bid = 1 - ask)

        auto_confirm : typing.Optional[bool]
            Confirm automatically the moment the taker accepts, instead of waiting for the confirm call

        rest_remainder : typing.Optional[bool]
            Rest any unfilled remainder on the book after execution

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateMakerQuoteResponse
            Successful Response

        Examples
        --------
        from rivermarkets import RiverMarkets

        client = RiverMarkets()
        client.rfqs.create_maker_quote(
            river_rfq_id="river_rfq_id",
            subaccount_id="subaccount_id",
            bid=1.1,
            ask=1.1,
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/rfqs/{jsonable_encoder(river_rfq_id)}/quotes",
            method="POST",
            json={
                "subaccount_id": subaccount_id,
                "bid": bid,
                "ask": ask,
                "auto_confirm": auto_confirm,
                "rest_remainder": rest_remainder,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    CreateMakerQuoteResponse,
                    parse_obj_as(
                        type_=CreateMakerQuoteResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def confirm_maker_quote(
        self,
        river_order_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Optional[typing.Any]:
        """
        Confirm an accepted quote.

        Parameters
        ----------
        river_order_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Successful Response

        Examples
        --------
        from rivermarkets import RiverMarkets

        client = RiverMarkets()
        client.rfqs.confirm_maker_quote(
            river_order_id="river_order_id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/rfqs/quotes/{jsonable_encoder(river_order_id)}/confirm",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    typing.Optional[typing.Any],
                    parse_obj_as(
                        type_=typing.Optional[typing.Any],  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def cancel_maker_quote(
        self,
        river_order_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Cancel an open quote, or refuse one that was accepted but not yet
        confirmed — the same venue call either way.

        Parameters
        ----------
        river_order_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from rivermarkets import RiverMarkets

        client = RiverMarkets()
        client.rfqs.cancel_maker_quote(
            river_order_id="river_order_id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/rfqs/quotes/{jsonable_encoder(river_order_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)


class AsyncRfqsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_maker_quotes(
        self,
        *,
        subaccount_id: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MakerQuoteListResponse:
        """
        Live (non-terminal) maker quotes for a subaccount.

        Parameters
        ----------
        subaccount_id : str
            Subaccount whose quotes to list

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MakerQuoteListResponse
            Successful Response

        Examples
        --------
        import asyncio

        from rivermarkets import AsyncRiverMarkets

        client = AsyncRiverMarkets()


        async def main() -> None:
            await client.rfqs.list_maker_quotes(
                subaccount_id="subaccount_id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/rfqs/quotes",
            method="GET",
            params={
                "subaccount_id": subaccount_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    MakerQuoteListResponse,
                    parse_obj_as(
                        type_=MakerQuoteListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def create_maker_quote(
        self,
        river_rfq_id: str,
        *,
        subaccount_id: str,
        bid: float,
        ask: float,
        auto_confirm: typing.Optional[bool] = OMIT,
        rest_remainder: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateMakerQuoteResponse:
        """
        Quote an RFQ from the /v1/ws/rfqs stream as a maker.

        Parameters
        ----------
        river_rfq_id : str

        subaccount_id : str
            Non-custodial subaccount quoting the RFQ

        bid : float
            YES-space bid: our price to buy YES

        ask : float
            YES-space ask: our price to sell YES (venue no_bid = 1 - ask)

        auto_confirm : typing.Optional[bool]
            Confirm automatically the moment the taker accepts, instead of waiting for the confirm call

        rest_remainder : typing.Optional[bool]
            Rest any unfilled remainder on the book after execution

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateMakerQuoteResponse
            Successful Response

        Examples
        --------
        import asyncio

        from rivermarkets import AsyncRiverMarkets

        client = AsyncRiverMarkets()


        async def main() -> None:
            await client.rfqs.create_maker_quote(
                river_rfq_id="river_rfq_id",
                subaccount_id="subaccount_id",
                bid=1.1,
                ask=1.1,
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/rfqs/{jsonable_encoder(river_rfq_id)}/quotes",
            method="POST",
            json={
                "subaccount_id": subaccount_id,
                "bid": bid,
                "ask": ask,
                "auto_confirm": auto_confirm,
                "rest_remainder": rest_remainder,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    CreateMakerQuoteResponse,
                    parse_obj_as(
                        type_=CreateMakerQuoteResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def confirm_maker_quote(
        self,
        river_order_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Optional[typing.Any]:
        """
        Confirm an accepted quote.

        Parameters
        ----------
        river_order_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Successful Response

        Examples
        --------
        import asyncio

        from rivermarkets import AsyncRiverMarkets

        client = AsyncRiverMarkets()


        async def main() -> None:
            await client.rfqs.confirm_maker_quote(
                river_order_id="river_order_id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/rfqs/quotes/{jsonable_encoder(river_order_id)}/confirm",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    typing.Optional[typing.Any],
                    parse_obj_as(
                        type_=typing.Optional[typing.Any],  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def cancel_maker_quote(
        self,
        river_order_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Cancel an open quote, or refuse one that was accepted but not yet
        confirmed — the same venue call either way.

        Parameters
        ----------
        river_order_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from rivermarkets import AsyncRiverMarkets

        client = AsyncRiverMarkets()


        async def main() -> None:
            await client.rfqs.cancel_maker_quote(
                river_order_id="river_order_id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/rfqs/quotes/{jsonable_encoder(river_order_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)
