# This file was auto-generated by Fern from our API Definition.

import typing
from ..core.client_wrapper import SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.fair_value_list_response import FairValueListResponse
from ..core.pydantic_utilities import parse_obj_as
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.http_validation_error import HttpValidationError
from json.decoder import JSONDecodeError
from ..core.api_error import ApiError
from ..types.fair_value_response import FairValueResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.client_wrapper import AsyncClientWrapper

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class FairValuesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_fair_values(
        self,
        *,
        subaccount_id: typing.Optional[str] = None,
        river_id: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FairValueListResponse:
        """
        List the caller's fair values, optionally scoped to one subaccount and/or one instrument.

        Parameters
        ----------
        subaccount_id : typing.Optional[str]
            Restrict to a single subaccount

        river_id : typing.Optional[int]
            Restrict to a single instrument

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FairValueListResponse
            Successful Response

        Examples
        --------
        from rivermarkets import RiverMarkets

        client = RiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )
        client.fair_values.list_fair_values()
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/fair-values",
            method="GET",
            params={
                "subaccount_id": subaccount_id,
                "river_id": river_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    FairValueListResponse,
                    parse_obj_as(
                        type_=FairValueListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def set_fair_value(
        self,
        *,
        subaccount_id: str,
        river_id: int,
        fair_value: float,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FairValueResponse:
        """
        Set the fair value for an instrument on a subaccount (insert-or-overwrite).

        Parameters
        ----------
        subaccount_id : str

        river_id : int

        fair_value : float
            Probability in [0, 1]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FairValueResponse
            Successful Response

        Examples
        --------
        from rivermarkets import RiverMarkets

        client = RiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )
        client.fair_values.set_fair_value(
            subaccount_id="subaccount_id",
            river_id=1,
            fair_value=1.1,
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/fair-values",
            method="POST",
            json={
                "subaccount_id": subaccount_id,
                "river_id": river_id,
                "fair_value": fair_value,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    FairValueResponse,
                    parse_obj_as(
                        type_=FairValueResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def delete_fair_value(
        self,
        subaccount_id: str,
        river_id: int,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Clear the fair value for an instrument on a subaccount.

        Parameters
        ----------
        subaccount_id : str

        river_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from rivermarkets import RiverMarkets

        client = RiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )
        client.fair_values.delete_fair_value(
            subaccount_id="subaccount_id",
            river_id=1,
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/fair-values/{jsonable_encoder(subaccount_id)}/{jsonable_encoder(river_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)


class AsyncFairValuesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_fair_values(
        self,
        *,
        subaccount_id: typing.Optional[str] = None,
        river_id: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FairValueListResponse:
        """
        List the caller's fair values, optionally scoped to one subaccount and/or one instrument.

        Parameters
        ----------
        subaccount_id : typing.Optional[str]
            Restrict to a single subaccount

        river_id : typing.Optional[int]
            Restrict to a single instrument

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FairValueListResponse
            Successful Response

        Examples
        --------
        import asyncio

        from rivermarkets import AsyncRiverMarkets

        client = AsyncRiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.fair_values.list_fair_values()


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/fair-values",
            method="GET",
            params={
                "subaccount_id": subaccount_id,
                "river_id": river_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    FairValueListResponse,
                    parse_obj_as(
                        type_=FairValueListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def set_fair_value(
        self,
        *,
        subaccount_id: str,
        river_id: int,
        fair_value: float,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FairValueResponse:
        """
        Set the fair value for an instrument on a subaccount (insert-or-overwrite).

        Parameters
        ----------
        subaccount_id : str

        river_id : int

        fair_value : float
            Probability in [0, 1]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FairValueResponse
            Successful Response

        Examples
        --------
        import asyncio

        from rivermarkets import AsyncRiverMarkets

        client = AsyncRiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.fair_values.set_fair_value(
                subaccount_id="subaccount_id",
                river_id=1,
                fair_value=1.1,
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/fair-values",
            method="POST",
            json={
                "subaccount_id": subaccount_id,
                "river_id": river_id,
                "fair_value": fair_value,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    FairValueResponse,
                    parse_obj_as(
                        type_=FairValueResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def delete_fair_value(
        self,
        subaccount_id: str,
        river_id: int,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Clear the fair value for an instrument on a subaccount.

        Parameters
        ----------
        subaccount_id : str

        river_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from rivermarkets import AsyncRiverMarkets

        client = AsyncRiverMarkets(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.fair_values.delete_fair_value(
                subaccount_id="subaccount_id",
                river_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/fair-values/{jsonable_encoder(subaccount_id)}/{jsonable_encoder(river_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)
