# This file was auto-generated by Fern from our API Definition.

from .get_prices_v1prices_river_id_get_request_interval import (
    GetPricesV1PricesRiverIdGetRequestInterval,
)
from .get_prices_v1prices_river_id_get_request_type import (
    GetPricesV1PricesRiverIdGetRequestType,
)

__all__ = [
    "GetPricesV1PricesRiverIdGetRequestInterval",
    "GetPricesV1PricesRiverIdGetRequestType",
]
